XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXX XXXXXXXXX
    XXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XX XXX XXXX XXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XX XXX XXXXXXX XXXXX XXXXXXXXXXX
    XXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX
    XXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX