# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto')),
                ('cuerpo', models.TextField(blank=True, null=True, verbose_name='Cuerpo')),
                ('remitente', models.CharField(max_length=64, verbose_name='Remitente')),
                ('destinatarios', models.CharField(max_length=4096, verbose_name='Destinatarios')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de envio')),
            ],
            options={
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='Link_Activacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=255, unique=True, verbose_name='Link Activación')),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('valido', models.BooleanField(default=True, verbose_name='Valido')),
                ('activado', models.BooleanField(default=False, verbose_name='Activado')),
            ],
            options={
                'verbose_name_plural': 'Links de Activación',
            },
        ),
    ]
