XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXX X XXXXXXXX XXXXXX X XXXXXXXXXX X XXXXX XX XXXXXXXXX X XXX XXX XXX XXXXXX XXXXX XXX X XXXXXXXX XXXX XXXXXX XXXXXXX XXXX XXXXX XXXXXX XXX X XXXXXXXX XXXXXXX XXXXXX XX XXXX XXXX XXXXXX XXX XXXXXXXXXXX XXX XXX XXXXX XX XXXXXXXX XXX XXXX XXXXX
            XXXXX XXXXX XXXX XXXXX XXXX XX XXX X XXXXXX XXXXXXX XXXXXX XX XXXX XXXX XXXXXXXX XXX XXXXXX XX XXXXXXXX XXX XXXX XXXXX XXXXX XXXXXXX XXXXXX XXXXXX XXXX XXXXXX XXXX XXX XXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXX XXXXXXXXXX XXXXXXXXX XXXXXX
            XXXXXXX XXXXXXX XXXX XXXXXX X XXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXX XXXX XXXXXXXXX X X XXXXXXXX XXXXX XXXXXXXX XXXX XXXXXX XXXXXX XXXXXXXX XXXXX X XXXXXX XXXXXX XXXXXXXXX X XXXXXXXX XXXXXX XXXXXXX X XXX XXXXXXX XXXXX XXXXX XX
            XXXXX XXXX XXXXXXXXXXX XXXXXX XX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXX X XXXXXX XXX XXXXXX XXXXX XXXX XX XXX XXXXXXX XXXXX XXX XX XXXXXXXXX XX XXX XXX XXXXXX XXX XXXXXXXX XXX XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX
    XXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX