XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXX XXXXX
  XXXXX	XXXXX	XXXXXX	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX	XXXXX	XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X
            XXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX
            XXXXXXXXX XXXXXXXXXXXXXX
  X
    XXXXXXXX XXXX   XXXXXXXXXXXXX
            XXXXXXXX XXXX   XXXXXXXXXXXXX
            XXXXXXXX XXX    XXXXXXXXXXXXX
            XXXXXXXX XXXXX  XXXXXXXXXXXXXX
            XXXXXXXX XXXXX  XXXXXXXXXXXXXX
            XXXXXXXX XXXXX  XXXXXXXXXXXXXX
            XXXXXXXX XXXXX  XXXXXXXXXXXXXX
            XXXXXXXX XXXXX  XXXXXXXXXXXXX
            XXXXXXXX XXX    XXXXXXXXXXXXX
            XXXXXXXX XXXX   XXXXXXXXXXXXXX
            XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX X XXXXXXXXXXXXXXXXXXXX X
  XXXXXX	XX	XXXXXXXX
  XXXXXXX	XXXXX	XXXXXXXX
  XXXXXXXX	XXXXX	XXXXXXXX
  XXXXXXXX	XXXXX	XXXXXXXX
  XXXXX	XXXXX	XXXXXXXX
  XXXXXXXXX	XXXXX	XXXXXXXX
  XXXXXXXXXXXX	XXXXXXXXXXXXXXXXXXXXXXXXXXX	XXXXXXXX
  XXX	XXXXXXXXXXXXXXXXX	XXXXXXXX
  XXXX	XXXXX	XXXXXXXX
  XXXXXXXX	XXXXX	XXXXXXXX
  XXXXXXXXX	XXXXX	XXXXXXXX
  XXXXXXXXXXX	XXXXX	XXXXXXXX
  XX	XXXXX	XXXXXXXX
  XXXXXXXX	XXXXX	XXXXXXXX
  XXXXXXXX	XXXXX	XXXXXXXX
  XXXXXXXXX	XXXXX	XXXXXXXX
  XXXXXX	XXXXX	XXXXXXXX
  XXXXXXXX	XXXXX	XXXXXXXX
  XXXXXXXXXXX	XXXXX	XXXXXXXX

XX
        XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXX
            X
                XXXXX XXXXXX
                XXXXXXXXXXX XXXX
            XX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXX XXXX
        XXX
    XXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX