XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XX XXXXXXXX XXXX XXXX XXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXX XXXXX XXXXXX XX XXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX X XX XX XXXXXX XXXXXXXXXX XXXXXX XXXXXX XXXXX XXXX XXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXX XX XXXXXX XXXXXXXXX XXX XX XXXXXXX XXXXXX XXXXX XX XXXXXXXX XXXXX XXXXXXXX
            XXX XXXX
    XXX XXXX XXXXX
      XXXXXXXX XX XXXXXXXX
    XXX
    
    XX XXXXXXXX
      XXXXXXXX XX XXXXX XXXX XXXXXXXX XXX XXXXXXX XX XXXXXXXX XXXXX XXXXXXXX XXX XXXX
      XXX
    XXXX
      XXXXX
        XXXXXXXX XX XXXXXXXX
      XXX

  XXX
  
XXXXXXXXX

XX XXXXX XXXXXXXXXX
XXXXX XXXXX

  XXX
   X XXX XXX XXXXXXXX
   XX
  XXXXXXXX XXX XXXXXXX XX XXX XXX
    XXX XXXXXX X X X XX
    XXXXXX XXX X XXXXXXXXXXXXX X XX X XXXX XX XX XXXXXXXX
    XXXXXXXXXXXXXX
    XXXXXX XXXXXXX
  XXXXXXXXXXX
  
  XXXX XXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX XXX
  XXXXXXX
  
XXXXXXXX

XXXXXXXXXXXXXXXXX

XXXXXXXX
  XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXX X
      XXXXX XXXXXXXXXX
      XXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
  XXX
XXXXXXXXX

XXX
XXXXXX XXXXXXXXXXXX XXX XXXXXXXXXXX XXX XXX XXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXXX
XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XX XXXXXXXX XXXXX XXXXXX XXX XXXXX XXXXXXXXXX XX XXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXX
  XXXXX
XXXX

XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX