XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXX X XXXXXXXXXXX X XXXXX XX X XXXX XXX XXXXXX XXXXXXXXXXXX XX X XXXX XXXXX XXXXX XXXXX XX XXXXXXXXXXX XXXXXXXXXXX XX XXX XX XX XXX XX XXXXX XXXXXXXXXXX X XXXXXXX X XXXXXXX XX X XX XXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXX XXXXXX XXX
            XXXXXXXX XX XXX XXXXXXXXXXX XXXX X XXXXXX XXXXX XXX X XXXXXX XXXX XXX X X XXXX XXXXX XXXXXXX XX XXX XX XX XXX XX XXX X XXXXXXX XX X XX XXXXXXX XXXXXX X XXX X X XXXXXXX XX XXXXX XXX X XX X XXXXXXX XXX X XXXXXXXXXXXXX X X XX X X XXXXXXXXXX X
            XXXXXXXXX X XX X XXX X XX XXXXXXX XX XXX X XX XXXXX XXXXXXX XX X XXXX XXXXXXX XX X XXXXXXXXX XXXXXXXX XX XXX XXXX X XXXXXXX XXX X XXXXXXXXX X XX XXXXX XXXXXXXXX XX X XX XXXXXXXXX XXXXXXXXXXXXX X XXX XXX X XX X XX X XXXX XX XXXX XXXXXXXXXX
            XX XXXXXXX X XXXXXX XXXXX XXXXXXXXXX XXX XXXXX X XXXXX X XXX X XX XXXXXX X XXX X XXXXX XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXX
        XXX
    XXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX