XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXX XXXXXXXX XXX XXX XXXXXXXXXXX XXXXXXXXXXX X X XXXXXXX XXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX X XXXXXXX XXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXX XXX XXXXXXX XXXXXX XXX XXXXXXX XXXXXXX
            XX XXXXXX XXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXX X XXXXXXX XXXXX XXX XXXXXXX XXXXXXX XX XXXXX X XXXXXXX XXXX XXX XXXXXXX XXXXXXX XX XXXX X XXXXXXX XXXXXX X XXX XXX XXXXXXX
            XXXXXXX XX XXXXXX XXX XXXXXXX XXXXXXX XX XXXXXX X XXXXXXXX XXXXX XXXXXX XXX XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX X XXXXX XXXXX XXX XX XXXXXXXXXXX XXX XXXXX XXX XXXXXXXXXXXXXX XX XXXXXXXXXXX X XXX XXXXXX XXXXXX XX
            XX XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXX XXXXX XXXX XXX XXX XX XXXXXXXXXXXX XX XXX XXXXXXX XXXXXXXXXXXX X XXXXXX XXXX XXXX XXXXXX XXXX X XXX XXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXX
        XXX
    XXXXXXXXX
    XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXX XX XXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX