XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXXXXXX XXXXXXXXX
    XXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX X XXXX XXXX X XXXXXXXXXX X X XXXXX XXXXXXXX XXXXXXX XXX XXXXXXXXXXX XXXXX XXXXXXXXXX X XX XXXXXXXXXX X XX XXXXXXXXXXXX X X XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XX XXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX X X XXXX XXXXXXXXXXXXXXXX X XXXXX XXXX X XXXXXXXXXXXX XXX XXXXX XXXX XX XXXXX XXXXX XXXXXXXXXXXXXXXX X XXXX XXX XX XXXXXXXXXXX
    XXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X
        XXX
    XXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX