XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX
XXXXXXXXX XXX XXXXXXXXXX XXXXXXXX X XXXXXXXXX XXXXXXXX XXX XXXXXX XXXXXXXXX
XXX XXXXXXXXXX XXX XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX
XXXXXX

    XXXXXX
        XXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXX
            X
                XXXX X XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                XXX XXXXXX X XXXXXXXX X XXXX X XXXXXXXXXXXX
                XXX XXXXX X XXX XXXXXXXXXXXXXXX
                XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXX XXXXXXXXXXX
                XXXX XXXXXX XXX
            X
            XXX XXXXXXXXX

            XXXXXXXX XXXXXXXXXXXXXXXXX
            X
                XXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
                XXX
                X
                    XX XXXXXXXXXXXXXXXXXXXXXXX
                    X
                        XXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X
                X
                XXXXX XXX
                XX
            X

            XXXXXXXX XXXXXXXXXXXXXXXX
            X
                XXX XXXXXXX X XXXXXXXXXXX
                XXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
            X

            XXXXXXXX XXXXXXXXXXXXXXXXXXX
            X
                XX XXXXXXXXXXXXXXXXXXXXXXXXX
                X XX XXX XXXXXXXX XXXXXX XX XXXXXX XXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX
                X
                XXXX
                X
                    XX XXXXXXXXXXXXXXXXXXXX
                    X XX XX XXXXXX XXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                    X
                X
            X

            XXXXXXXX XXXXXXXX
            X
                XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
                XXXXXXXXXXXXXXXXXXXX
            X
        XXXXXXXXX
    XXXXXXX

    XXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX
    XXXXXXX

XXXXXXX