XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXX XXXXXXXXXXXX X
        XXXXXX XXXXX
        XXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXX XXXXXXXXXXXXXX X
        XXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXX XXXXXXXXXXXXX X
        XXXXXX XXXXXX
    X
    
    XXXXXXXXXXXXX XXXXXXXXXXXXXX X
        XXXXXX XXXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXX XXXXX XXXXX XX X X XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXX XXXXXXXXX XXXXXX XX XX XXXXXXXXX X XXX XXXX XXXXXX
            XX XX XXXXXXXXX XXXXX X XXXXXXXXX XX XXXXXX
            XX XXXXXXXXXXX X XXXXXXXXXXX X XXXX XXXX XXXXXX XX X XX XX XXXXXXXXXX XXXXX X XXXXXXX XXXXX XX XXX XXX XX XXX XX XX XXXX XX XXXXXXXXXXXXX X XXXXXXXXXXXXXX X XXXX XXXXXXXX XXXX XXXX X X XX XXXXXXXX
                XXXXX X XXXX XXXX XXX XXXX XXXXXXXX XXXX        X XX XXXXXXX XXXXX X XXXX XXXXXXX XX XXXX X XXXXX XXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXX XX XXXXXX XX XXXXXXXXXXX X XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX X XXX XXXXXXXXX
                XXXXXX XXXXXXXX XXXXXX XX X XXXXX XXXXXXXXX X XXXXXXX XXXX XXXXXXXXX XX XXXXX XXXXXXX XX XX XXXXXXXX XX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX X XXXXXX XXXXXXXX XXXXXX XX X XXXXX XXXXXXXXXXXXXXXXXXX X XX XX XXX XXXX XXXXXXXXXX
                XX X XXXXXXXX XXX XX XXXXXXXX XXXX XX X XXXXXXXXX XX XXX XXXXX XXXXXXX XXXX XXXX XXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX
    XXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XX XXX XXXXXXXXXX X XXXX XXX XXXXXX XXXXXXXXX XX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX