XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X
    
    XXXX X
        XXXXXXXXXXXXXX XXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XX XXXXXX XXXX XX XXXX XXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXX X XXXXXXXXXXXX XXXXXX XXXXXXXXXXX X XX XXXXXXXXX XXXXXXXXXXXXXX X XXXX XXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXX
            XXXXXXXXXX X XXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXX X XXXXX XXX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXX XXXXX X XX XXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX X XXXX XXXXXXXXXXXXXXXXXXXXX X XXXXX XX XXXXX XXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXX XXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX X XXXXX XXXXXXXXXX XX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX X X XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXX X XXXXXXXX XXXXXXX X XXXXXX XXXXXXXX X XXXXXXX
            X XXXXXXXX XXXX XXXXXXX XXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX X XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXXXXXXX
            X
                XXXXXXXXXXXXX XXXXXXXXXXXXXX
            XX
            XXXXXXXX X
        XXX
    XXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX
XXXXXXXXXX