# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva_dict', models.TextField(blank=True, null=True, verbose_name='Reserva (stores in session)')),
                ('paypal_payment_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='ID Paypal Payment')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de creación')),
                ('total_pagado_euros', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total Pagado €')),
                ('approval_url', models.URLField(max_length=255, verbose_name='URL de aprovación')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Paypal_App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre')),
                ('modo', models.CharField(max_length=7, verbose_name='Modo ("sandbox" o "live")')),
                ('mail_vendedor', models.EmailField(max_length=64, verbose_name='E-Mail vendedor')),
                ('client_id', models.CharField(max_length=80, unique=True, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=80, unique=True, verbose_name='Client SECRET')),
                ('return_url', models.URLField(max_length=255, verbose_name='Return URL')),
                ('cancel_url', models.URLField(max_length=255, verbose_name='Cancel URL')),
                ('en_uso', models.BooleanField(default=False, verbose_name='En uso')),
            ],
            options={
                'verbose_name_plural': 'Paypal Apps',
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='paypal_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.Paypal_App'),
        ),
    ]
