XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXXXX X
        XXXXXXX XXX XXXXX XXXXX
        XXXXXXX XXXXXX
        XXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXX XXX X
        XXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXX XXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXXXX XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXX XXXXX
        X
            XXX XX X XXXXX
            XXX X X XX

            XXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXX
            X
                XXXXXXXXXXXXXXXXXXXXXXXXXXX X X X X XXXXXXXXXXXXX X X X X XXXXXXXXXXXXXX X X X X XXXXXXXXXXXXX
                XXX XXXXXX X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXX XX XXXXXXXXX XX XXXXXXXXXXXX XX XXXXXXXXXX
                X
                    XXXXXX XXXXXXX XXXXXXXXX X X XXXXXXXXXXXXXXXXX X XX XXXX X X XXXXXXXXXXXXXXX
                    XX X XXXXXX
                X
                XXXX
            X
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
            XX XXXX XXXXXX XXXXXX XXXX
        X

        XXXXXXXX XXXXXXXXXXX
        X
            XXX XXXXXX X X
                XXXXXXXXXXX XXXXXXXXXXX
                XX XX XXXXXXXX
                XXXXXXXXX XXXXXXXXXX
            X
            XXX XXXX X XXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXX
        X

        XXXXXXXX XXXXXXXX
        X
            XXX XXXXXX X X
                XXXXXX XXXXXXXXXXX
                XX XX XXXXXXXX
                XXXXXXXX XXXXXXXXXXX
                XX XX XXXXXXXX
                XXXXXXX XXXXXXXXXXX
                XX XX XXXXXXXX
                XXXXXX XXXXXXXXXX
            XX
            XXX XXXX X XXX XXXX XXX XXXX
            XXXXXX XXXXXXXXXXXX XXXXXX
        X

        XXXXXXXX XXXXXXXXXX
        X
            XXX XXXXXX X X
                XXXXXXX XXXXXXXXXXX
                XX XX XXXXXXXX
                XXXXX XXXXXXXXXXXX
                XX XX XXXXXXXX
                XXXXXX XXXXXXXXXXX
                XX XX XXXXXXXX
                XXXXXXXXXXX XXXXXXXXXX
            XX
            XXX XXXX X XXXX X XX XXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXX
        X

        XXXXXXXX XXXXXXXXX
        X
            XXX XXXXXX X XXX
            XXXXXX XX XXXXXXXXXXX X XXXXX
            XXXXXX XX XXXXXXXX X XXXXX
            XXXXXX XX XXXXXXXXXX X XXXXX
            XXXXXX XXXXXXX
        X

        XXXXXXXX XXXXXXXXXXXXXXXX
        X
            XXX XXXXXXX X XXXXXX XXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXXXXXX XXX XXXXXXXX XX XXXXXXXXXX XXXXXXX X XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXX X X XX X X XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX
        X

        XXXXXXXX XXXXXX
        X
            XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
                XXXXXXXXXXXX XXXXX
                XXXXX XXXXXXXXXXXX
                XXXXXXXXX XXXXX
            XXX
            XXXXXXXXXX
        X

        XXXXXXXX XXXXXXXXX
        X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
            XXXXXXXXXXXXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXX X XXXXX
    XXXXXXXXX
    XXXX XXXXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX