XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXXXX X
        XXXXXXX XXX XXXXX XXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXX X XXXXXXXXX XXXXXX XXXXXXXXXXXX X XX XXXXXX X XXXXXX XXXXX XXX X XX XXXXXX X XXXXX XXXXXXXXX XXXXXX XXXXXX XXXXXX X XXX XXXXXXXXX XX XXXXXX XXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXX XX XXXXXX X XXXXXX XXXXX
            XXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXX XX XXXXXXXXX XX XXXXXX X XXXXXXXXXXXX XXXXXXXX XX XXX X XX XX
            XXX XX X XXX XX X XXXXXXX X X XXXX X XX XXXXXXX XXX XXXXXX XXX XXXXXXXXXXX XXXXX XXX XXXXXXXXXXXXXXXX XXXX X X XX XXXXXX XX XXXXXXXX XXXXXXX
                XXX XXXXXX X XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX X XX X X XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXXXXXX
        XXX
    XXXXXXXXX
XXXXXXXXXX