XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX

    XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
            XXXXX
            XXXX X
                XXXXXXXXXXXX XXXXXXXX
                XXXXXXXXXX XXXXX
            X
            
            XXXXXXXXX X
                XXXXXX XXXXX
                XXXXXXX XXXXXX
            X
        XXXXXXXX
        XXXXXXXX
            XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
                XXXXX XXXXXX
                XXXXXXXXXXXXX
                X
                    XXXXXX XXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXX XXXXX
                XX
                XXXXXXXXXXXXX XXX
                XXXXXXXXXXXXXXXX
                X
                    XXXXXXXXXXX XXXX
                XX
                XXXXXXXXXXX
                XXX
                XXXXXXXXXXXXXX
                X
                    XXXXXXXX XXX
                    XXXXXXXXXXX XXXXXXXXX
                    XXXXXXXXXXX XX XXXXX
                XX
                XXXXXXXXXXXXX
                X
                    XXXXXXXXXX XXXX
                X
            XXX
        XXXXXXXXX
    XXXXXXX

    XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXX

XXXXXXX