XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXXXX X
        XXXXXXX XXX XXXXX XXXXX
        XXXXXXXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXX X
        XXXXXXX XXXXX
        XXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXX XXX X
        XXXXXX XXXXXX
        XXXXXXXXXXXX XXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX X XXXX XX X XXXX XX XXX XXXXXXXXX XXXX X XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX X X XXXXX X XXXXXXXXX XXXXX XXXXXXXX XXXXXXXXX X XXXXX X XXXXXXXXXX X XXXXX XXXXXXXXXXX XXXXX XX XX X XXXXXX X XX XXXX X X XXXXXXXXXXXXXXXX XXXX X XXXX XXXXXXXX
            XXXXXX XXXX XXXXXX XXXXXXXXX X XXXXX XX XXXXX X X XX XXXXX XXXXX XXXX XXXXXX XXXX XXXXXX XXXXXXXXX X XXXXX XX XXXXX X X XX XXXXX XXXXX X X XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXX X
        XXX
    XXXXXXXXX
    XXXXXXXXX XXXXXXXXX XXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX