XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XX XXXX XXXXXXX XXXX XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXX X XXXXXXXXXXXXXXXXX XXXXXX X XXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXX X XXXXXXX X XXXXXXXX XXXXXXX X XX XXXXXXX
            XXXXXXX X XX XXXXXXXXXXXXX XXXXXX X XXXXXX XXXXXXXXXX X XX X XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXX X XXX XX XXXXXXXXX XXXX X XXXXXXXX X XXXXXXX XXX XX XXXXX X XXXXXXXXXXX XXXXXX X X XX X XXXXX X XXXXXXX XXXXXX XXXXXXX XXXXX XXXXX XXXXXX X
            X XXXXXX XXXXXXXXXXX X XXXXXX XXXXX XXXXXXXXXXXX XXXXXX X XXXXX X XXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX X XXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXX XXXXXXX XXXXX XXXXXX XXXXXX X XXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXX XXXX XXXXX XXXX XXXXXXX XXXXX XXXXXX XXXXXX X XXXX X XXXXXXX XX XXXXXXXX XXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXX XXXXXX XXXXX X XXXXXX XXXXXXXX X XXXXXXXXXXX XXXXXXX X XXXX X XXXXXXXXXX XXXXX X XXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXX X X XXXXXXXXXXX XXXXXXXXXXX X X XXXXXX XXXX X X X XXXXXXXXXXX X X XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX X XX X XXXXXXXXXX XXXXXX X XX X XXXXXXXXXX XXXXXX X XXXXXXXXXX XXXXXXXXX X XXXXXXXX XXXXX X XXXX X XXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXXXX XXXXXXXX X XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXX
        XXX
    XXXXXXXXX
    XXXXXX XXXX XXXX XX X XXXXXXXX XX XXX
        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX