XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX

    XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
            XXXXX
            XXXX X
                XXXXXXXXXXXX XXXXXXXX
                XXXXXXXXXX XXXXX
                XXXXXXXXXXXXXXXXX XXXXXXXX
            X
            
            XXXXXXXXX X
                XXXXXX XXXXX
                XXXXXXX XXXXXX
            X
        XXXXXXXX
        XXXXXXXX
            XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
                XXXXXXX XXXXXXXXX
                XXXXXXXX XXXXXXX
                XXXXXXXXXXXXX
                X
                    XXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXX XXXXX
                    XXXXXXXXXXX XXXXXXXXXXXXXXX
                    X
                        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                    XX
                    XXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                    X
                        XXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXXXXX
                    XX
                    XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                    X
                        XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXX XX XXXXXXXXXXXXX
                    X
                XX
                XXXXXXXXXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXXXX XX
                XXXXXXXXX XXXXX
                XXXXXXXXXXXXXXX
                X
                    XXXXXXXXXXXXXXX XXXXXXX
                XX
                XXXXXXXXXXXX X
                X
                    XXXXXXXXXXX XXXXXX
                    XXXXXXXX XXXXXXXX XXXXX
                    XXXXXXXXXXXXXXXXXXX XXXX
                XXX
                XXXXXXXXX X
                X
                    XXXXXXX XXXXXXXXX
                    XXXXXXXX XXXXXXXXX
                    XXXXXXXXXXXXX XXXXXXXXX
                    XXXXXXXXXXXXX XX
                    XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX
                X
                    XXXXXXX XXXXXXX
                    XXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXXXXX XX
                    XXXXXXXXX XXXXXXXX
                    XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX
                XXXXXXXXX
                X
                    XXXXXXXXXXXXXXXXXXX XXXX
                XX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXXXXXXX
                X
                    XXXXXXXXXX XXXX
                X
            XXX

            XXXXXXXX XXXXXXXXXXXX
            X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XXXXXXXXX
    XXXXXXX

    XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX

XXXXXXX