"""
Django settings for Ontraveline project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os, sys
from django.core.urlresolvers import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4v5#0s(n%wdi@$q@td3es24$3^m03^i_wk_v-31lspj66!5+k5'

# Application definition
INSTALLED_APPS = [
    # Apps Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps Propias
    'website',
    'usuarios',
    'servicios',
    'mensajes',
    'social',
    'administracion',
    'emails',
    'pagos',
    'blog',
    'twilio_app',

    # Apps de Terceros
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LANGUAGE_CODE = 'en-us'

ROOT_URLCONF = 'Ontraveline.urls'

LOGIN_URL = reverse_lazy('accounts:login')

LOGOUT_URL = '/accounts/logout/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Ontraveline.wsgi.application'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Configuración de caché
CACHE_BACKEND = 'locmem:///'

# INTERNATIONALIZATION
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# EMAIL SMTP SERVER CREDENTIALS
# Info here: https://ph.godaddy.com/help/configuring-mail-clients-with-cpanel-email-8861?v=1
EMAIL_HOST = 'mail.ontraveline.com'
EMAIL_HOST_USER = 'contact@ontraveline.com'
EMAIL_HOST_PASSWORD = 'Ipvce/*-789'
EMAIL_PORT = 25
EMAIL_USE_TLS = True

MEDIA_URL = '/media/'
STATIC_URL = '/static/'

from Ontraveline.settings__dev import *
from Ontraveline.settings__prod import *