XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXXXX X
        XXXXXXX XXX XXXXX XXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XX X XXXX XXXX XX XXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXX XX XXX X XXXXXXXXXXX XXXXXXXXX XXX XXXXXXXXX XXXX XXXXX XX XX XXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXX XXXXXXX XXXX X XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXX
            X XXXXX XXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXX XXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXX XXXXXXX XXXX XXXX X XXXXX XXXXXXXXXXX XXXXX XXX XXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XX XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXX XXXX X XXXXXX XX XXXXXXX XXXXX XXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX X X XXXXX XX XXXXXXXXXX XXXXX XXX XX XXXXXXXX
            XXXXXXXXXXX XX XXXXXXXX XXXXXXX XXXXXXXX X XXX XXXXXXX XXXXXXXXX XXX XX XXX XXXXXXXX XXX XX X XXX XXX X XXXXXXXXXX XXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXX XXXXXX X XXXXXX X X XXXXXXXXXXXX XX X XXXX XXXXXX XXXX XXXXXXXXXXXX
            XX XXXX XXX X XXX X X XXX XX XXXXXXXX XXXXXXXXXXXX X XXXXXX XX XXXXXXXXX XX XX XXXX XXXXXX X XXX XXXX XXXXXX XX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX XXXX XXXXXX X XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX X XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
            X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXX X XXXXXX XX XXXXXXXXX XX XX XXXX XXXXXXXXXXXX X XXXXXXXXXXX XXXX XXXXXX XX XXXXXXXXX XX XX XXXX XXXXXXXXXXXX X XXXX X XXXXXXXXXXX XXXX XXXXXX XX XXXXXXXX XX XXXXX XXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
            X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX XX XXXXXXXX XX XXXXX XXXX XXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXXXXXXXXXX XXXX X XXXXXX XXXXXXXXXXX XX XXXX XXXXXXXXXXXXX XXXXXX XX X XXXXXX XXXX XXXXXXXXXXXX X XXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
            X X XXXXXXXX X XXXX X X XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXX XXXXXX XXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX XXX X X X XXXXX X XXX X XXXXXXX XXXXXXXX XXXXXXXX XX X XXXXXXX XX XXXXXXXX XXXXXXXXXXXXXXXXX XX X XXXXXX XX XX
            X XXX XXXX XXXXXXXXXXXXXX
                X XXXXXXXXXXXX X XXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXX X XXXX X XXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX XX X XXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXX XX X XXXXXX XX XX X XX XXXX XXXXXXXXXXXXXXX
                X XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXX X XXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X XXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXX XX
                X XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXX XXXXXXXX XXXXXXXXXXXXXXX XX X XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXX XX X XXXX XXXXXXXXXXXXX X XXXXXX X XXXXXXXX X XXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                XX X XXXX XXXXXXXXXXXXX X X XXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXX XX X XXXX XXXXXXXXXXXXXX X XX X XXXXXXXXX X XXXXX XXXXXXXX XXXXXXX XXXXXXX XXXX XXX XXXXX XX XXXXXX XX X XXXXXXXX X XXXXXXXX XX XXXXXXX XXXXXXX XX X XXXXXXX X XXXXXXX XX XXXXXX
                XXXXXXXXX XXX XXXXXXX XXXXXXX X XXXXXXXXXX X XXXXXXXX XXXX X XXXXXXX XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XX X XXXXXX XX XXXXXXXXXXXX X X XXXX XXXXXXXX X XXXX XXXXXXX X X XXXX XXXXXX XX XXXXXXX XXX XX XXXX
                XXXXX X X XXXX XXXXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX X XXXX XXXXXXXX X XXXX XXXXXX X X X XXXXXXXXX XXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXX XX XXX XXXX XXXX XXX XXXXX XX
                    XXXXXX XXX XXX XXXXXXXX XXXXXXXX XX XXXXXXX XXXXXXX XX X XXXXXXX XXXXXXX XX XXXXXX XXXXXXXXX XXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXX XXXX XXXXXXX XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX X XXXXXX XX XXXXXXXXXXXX X X XXXX XXXXXXXX X XXXX
                    XXXXXXX X X XXXX XXXXXX XX XXXXXXX XXX XX XXXX
                    XXXXX X X XXXX XXXXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXX XX XXXXXXXXXXX X XX XXXX XX XXX XX XXXX XX XXX XX XXXX
                        XXXXX X X XXXX XXXXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX X XXXX XXXXXXXX X XXXX XXXXXX X X X XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX X XXX XXXXXXXXXX XXXXXXX XXXX XXX XXXXXXXX XXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XX
            XXXXX XXXXXXXXXX
        XXX
    XXXXXXXXX
    XXXXXXXXX XXXX XXXX XXXXXX XXXXXXXX X
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX
XXXXXXXXXX