XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXX XXXXXXXXX
    XXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XX XXXXXXX XXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XX XXXX XXXXXXX XXXXX XX XX XXXXX XX XXXXXXX XX XXX XXXXXXX X XXXXXXXXX XXXXXXXXXX XXX XX XXXXXXX XXX XXXXXXXX XXXXXXXXX XXX X XXX XXXXX X XXX XXX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXX XXX X XXX X
            XXXXXXXX XXXXX X XXXXX X X XXXXXX XXX X XXXXXXXXX XXX X XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
    XXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXX
            X
                XXXXX XXXXXX
                XXXXXXXX XX
                XXXXXXXXXXXXXXXXXXXXXXX XXXXX
            XX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XX
            XXXXXXXXXXXXXX XXXX
        XXX
    XXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX