XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXXXXX XXXXXXXXX
    XXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX X XXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX X XXXX XX XXXX XXXXXXX XXX XXXX XXX XXXXXXX X XX XXXXXXXX XX XXXXX XXX XX XXXX XXXXXXX XX XXXXXXX XX XXXX XX XXXXXXXX X XXXXX XXXX XXX XXX XX XXXXXXX XXXXXXXXX XX XXXXX XXXX XXXXXXX XXXXXX XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXX XXXXXXXXXXX XX XXXXXX XXXXXXX XX XXXXXXXXXXXXXXXX XXXX XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXX XXXXXX XX XXXXXX XX XXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXX XXXXXX XXX XXXXXX XX XXXXXXXXX XXXX XXXXX XXXXXX X XXXX XXX XXXXXXX XX XXXXXXX XXXXXX XXX XXXXXXXX XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXX X XXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXXXXXXX XXX
            XXXXXXXX XXXXXX XXXX XX XXXXXXXXXXXXX X XXX X XX XXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXX X XXX X XXXXXXXXXXXX X XXX XXX XX XX XXXXXXXXXXXXX
            X XXXX XX XXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXX
                X XXX X XXXXXXXXXXXX X XXX XXX XX XXXXXXXXXX XXXXXXXX X XXXXX XXXXXX XX XXXXXXXX XXXXX XXX XXXXXXXXXXXX XXXXXXXX X XX XXXXXXXXXXXXXX XXXXX XXX XXXXXXXXXXXX XXXXXXXX XX XXXXXXXX XXXXXX X XX XXXXXXXXXXXXXXXX
                    XXXXX XXX XXXXXXXXXXXX XXXXXXXX XX XXXXXXXX XXXXXX X XX XXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXX XXXXXXXXXXX
    XXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXXXX
        XXX
    XXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX