XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXX XXXXXX XXXX XXXXXX XXXXXX XXXXX XXXX XXXXX XXXXXXXX XXX XXXXXX XXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXX XXXXXX XXX XXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX X X X XXXXXX XX X XX X X X XXXXX XX X XX XXXXXX X X XXXXXX XXXXX
            XX X XXXX XXXXXXXX XXXXXXXXXX XXXXXXXXX XX XXXX XX XX XXXXXX XXX XXXXXXXX XXXXX XX XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXX XXXXXXX XXXXXXX XXX XXX XXXXXX XXXXXXXXX XXXXXXX
            XXXXXXXXX
                XXXX XXXX XXXX XXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX XXXXXXXXXX XXXX XXX XXX XXX XXXXXXXXX XXXXXXXXXX XX XXXX XXX XXXXXX XXXXXXXXXX XXXXXXX X XXXXXXXXXXXX XX XX X X X X
                XX X X X X X X X X X X
                    XX XX XX
                        XX XXXXX XXXX XXX XXXX
                            XXXX XXXX XXXXX XXX XX XX XX XXX XX XX XXXX XXX XXX XXX XXX XXX XXX XX XXX XX XXX XX XX XXX
                                XXXX XX
                                    XX XX X X X X X XXXXXXX XXXXXXXX X XXX XXXXXXXXX XXXXXXXXX XXX XXXXXXXXX XX XXXX XXXXXX XXXXX XXX XXXXX XXX XXX XX XXX XXXXX XXXXXXX XXXXXX XXXXX XXXXXXXX XXXXXX XXXXX XXXXX XXXXXX XXXXXX XXXXXXXXX XXXXX XXXXXXXX XXXXX
                                        XXXXXX XXXXXXXXXX XXXX XXXXXXXXX XXXXX XXXX XXXXX XXXXXXXXX XXXXXXXXXXX
    XXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXX
            X
                XXXXX XXXXXXXX
            XX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XX
            XXXXXXXXXXXXXX XXXX
        XXX
    XXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX