XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXX XXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXX XXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXXXXX XXX XXXXXXXXXXXX XX XXXXX XXXXX XX XXXXXXXXXXXXXXXXXXXXXX X X
            XXXXXXXX
                XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
                    XXXXXXXXXXXX XXXXX
                    XXXXXXXXXXXXXXXXXXX XXXX X XXXXXXXXXXXXXXXXXX XXXXX
                    XXXXXXXXXXXXXXX XXXXXXXXXXX
                    X
                        XXXXXXXXXXXXXXX
                    X
                XXX
            XXXXXXXXX
            XXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXX XX XXX XXXXXXXXXX X XXXXXXXXXXX X X XXXXXXXX XXXXXXXXXXXXXX X X XXX XXXXX X XXXXXXXXXXXXXXXX
            XXXX X XXXXXX X XXX XXXXX X XXXXXXXXXXXXXXXX XXXX X XXXXXX XXXXXX X XXXXXXXXXXX XX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XX XXXXXXXXXXX XX XX XXXXXXX X XX XXXXXXXXXXXXXXXXXX XX XXXXXXX X X XX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX X XXXXXXXXXXXXX X XXXXXXX X X X XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXX XX XXXXXX XXXXXX XX XXX XXXXXXXXXX X XXXXXXXXXXX X XXX XXXX X X XXXXXXXXXXXX X
            X XXXXXXXXXX XXXX X XXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXXXXX
                XXXXX XXXXXXXX X XXXXXXXXXXXX X XXXX X XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XXXX XXXXXXXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXX X X X X X XXXXXXXXX X XXXXXXXXXX X XXXX XXXXXXXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXX X X X XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX X
                XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXX XXXX XXXXXXX XXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XX XXXXXXXX XXXXXXX XX XXX XXXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXX XX XXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXX XXXX XX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX X XXXX XX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX XXXXX X XXXX XX XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX X XXXX XXXXX XXX XXXXXX XXXXXX XXX XXXXXX X X XXXXXXXX X XXXX XX XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                X XXXX XXXXXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXX XX XXX XXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXX XXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXX XXXXXXXXX X XX XXXXXXX XXXXXXX XX XXX XXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXX XXXXXX XXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXX XXXXX X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXX XXXXXXXXXX XXXX XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX
    XXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX