XXXXXXXXX XXXXX
XXXXXX

    XXXXXX
        XXXXX XXXXXXXXXXXXXXX XX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
                    XX XXXX XXX XXXXX XXXX XX XXXXXXXXXXXXX
                    XX XX XXXX XXXX XXX XXXXXX XXX XXXX XXXXXX XXX XXXXXXXXXX XXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XX XXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX XXXXXXXXXXXXXXX
                    X
                        XX XXXXX XXXXXX XX X XXXXX XXXXXX
                        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXX
                    XX
                    XXXXXXXX XXXXXXXXXXXXXX
                    X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X
                XXX
            XXX
        XXXXXXXXX
        XXXXXXX
            XXXX X
                XXXXXXX XXXX XXXXX
                XXXXXXXX XX
                XXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXX
                XXXXXXXXXX XXXXX
            X
            
            XXXXXXXX X
                XXXXXXXX XXXXX
                XXXXXXXXX XXXXXXXXX
                XXXX XXXXX
                XXXXXX XXXXX
            X
            
            XXXXXXXXX X
                XXXXXXXXXX XXXXXX
                XXXXXXX X XXXXX
            X
        XXXXXXXX
    XXXXXXX

    XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXX

XXXXXXX