XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXXXX X
        XXXXXXX XXX XXXXX XXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XX XXXXXXX XX XXXX XXXXXXX XX XXXXXXXXX XX XXXXXXXXX XXX XXXX XXXXXXXX XXXX XXX XXXXXX XXXXXXXXX XX XXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX X XXX XXXXXX XXXXXX XXX XXXXXXX XXXXXX XXX XXXXXXXXX
            XXXXXX X XXX X XXXXXX XXXXX X XXXXXXX X XX X X XXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX X XXXXXXXXXX X XXXXX XXXXXXXXXXX X XXXXXX X XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXX X XXXXXX XXXXXXXX X XXXXXX X XXXX XXXXXXXXXXXXXXXXXXXX XX XXXXX
            XXXXXXX X XXX XXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXX XXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXX XXXXX XXX XXXXXX X XXXXX XXXXXXXXX XXX XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX X XXX XXXXXX X XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X XXXXXX XXXXXX X X XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXX
        XXX
    XXXXXXXXX
    XXXX XXXXXX XXXX XXX XXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX
XXXXXXXXXX