XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXX XXX X X XXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XX XX XXXXXXX XXXX XXX XXXXXXX X XX XXXXXXXXXX X XX XXXXXXXXX XX XXXXXX XX XXXXXX XXXXXXXXXXX XX XX XX X XX XX XXXXXXXX XXX X X XXXXXXX
            XX
                XXXXX X XXXXXXX XXX X X XX XXXXX XXXXX XX X X XXXXXXXXXXXXX X X XXXXXXX X XXXXXXXXXXXXX XXXXXXX X   XXXX X X X XX XXXX XXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX XXXXXX X XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXX X XXXXXXX X XXXXX
                XXXXX X XXXX XXXXXXXXX X XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXX X XXXXXXX X XXXXX XXXXX X XXX XXXXXXXXXXXX XXXXXX X XX XXXXXXXXX X XXXXXX XXXX XXXXXXXXXXXXX X XXXXXXXXXXX X XXXXX X XXXX X XXX X XXX XXXXXXXXXXXXXXXX XXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXX XX XXX XXXXX X XXXXXX X XXXXXXXXXX XXXXXX X XXXXXX X XXXXXXXXXX XXXX XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X X XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXXX
        XXX
    XXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX