XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXX
  XXX XXX XXX XXX X XXXXXXXX XX XXX
  XXXXXXX XXXXXXXXXX XX XXX XXXXXXX XXXXXXX XXX
  
            XXXX XXXXXXXXX 
                 
                    XXXXXXX
                     XXXXXXX XX   XXXX XXXXXXXXX 
                        XXXXXXX
                        
                        XXXX XXXX XXXX XXXX XX XXX 
                        
                            XXXX
                        
                
                
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXX 
        XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        X
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            X
                XXXXX XXXXX
                XXXXXX XXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXX XXXX
            XXX
        XXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXXXX
        XXX
    XXXXXXXXX
    XXXXXXXXX
    XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXX XXXXXXXXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX