XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXXXX X
        XXXXXXX XXX XXXXX XXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX X XXXX XXXXXXX XXXXXX XXXXXX XXXXXXX XXX X XXXXXXX XX XXX XXXXXXX XXX XXXXXX XX XXX XXXXXX XXXXXXX XXXXXXXXXX XXX XX XXX XXX XXXXXXXXXX XXXX XXXX XX X XXXXXXXX XXXXXX XXXX X XXXXXX XXX XX XXXXXX X XXXXXXX XX X XX XXXXXXX XXXX XXXX XXX XXXXX XXXX
            XX XXXXX XXXXX XXX XXXXXXX XXXXXXXXXXX XXX XXXX XXXX XXXX XXXX XXXXXX XXX XXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXX XXX XXX XXX XXX XXXXXXXXXX XXXX XXXX XX XX XXXXXXXXX X XXXXX XXX XXX XXXX XX XX X X XXXXXXXX XXX X XX XXXX XXX XXXX XXXX XXXXXX
            XXX XXXX XX XX X X XX XXX XXXX XXXX XX XXXXXXX XX XXX XXXX XXXXXX XXX X XX XXXX XX XXXXXXX XXX X XX XXXX XX XXXXXXX XXX X XX XXXX XX XXXXX XXX X XX XXXX XX XXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXX XXXXXXX XX XXXX XX X XXXX XXXX XXXX XX XX XXXXX
            XXXXXX XX XXXXXXXXXX XX X XXXXX XXX X XX XXXX XX XXXXX XXX X XX XXXX XX XXXXX XXXXXXXX X XXXX XXXX XX XXXXXXXXX XXX X XX XXXX XX XXXXXX XXXX XXXX XX XXX XXXXX XXXX XXXX XXX XXXXX XXXX XXXX XX XXXX XX XXXXX XXX XXXXXXX XX XXX XXXXXXXX XXXX
            XXXXX XXXXXXXXX XXX XXXX XXXXXXX XX XXXX XX X XXXX XXXX XXXX XX XX XXXXX XXXXXX XX XXXXXXXXXX XX X XXX XXXXXX XX XXXX XXX XXXX XX X X X X X X X X XXXXXXXXX X X XX XXX XX XX X XXXXXXX X X XXXXXXXXX XXXX XX XXX XXXXX XX XXXXX XX XXX XXXXXXXX
            XXXXXXXX X XXXX XXXX XX XX XXX XXX XXXXX XX XXX XXXXXXXXXXXXX XXXXXXXX XXX XXXXX XXXX XXXX XX XXXXXXXXX XXXX XX XX XX XXX XXX XXXXX XXXXXX XXXXXXXX X XXXX XXXX XX XXX XX XX XXXX X XXX XXXXX XXXX XX XXX XXX XX XXX XXXX XXX XXX XX XXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XX XXX XXXX XXX XXX XXXXXXXXXX XXX X XX XXXX XX XXXXX XX XX XXXXXXXXXXX XXXXX XXXXXXX XXX XXXXXXX X XXXXXXX XXXX XXXX XX XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXXXXXX
        XXX
    XXXXXXXXX
    XXXX XXXX XXX XXXXXXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX