XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX

    XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX X
                XXXXXX XXXXXX
                XXXXXXX XXXXX
            X
        XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX
            X
                XXX XXXXXXX X XXX XXXXXXX
                XXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXX X XX X X XX XXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
                    XXXXXX XXXXXXX
                XXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
        XXXXXXXXX
    XXXXXXX

    XXXXXX
        XXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
        XXXXXXX XXXX XXXXXXXXXXXX XXX XXXX XXXXXX XX XXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XX XXXXXXXX XXX XXXXXXX XXXXXXXXXXXX XXX XXXXX XXX XXXXXX XXX XXX XX XXXX XX XXX XXXXX XXX XXXX XXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXX XXXXXX XXX XXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXX XXXX XX XX XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX

XXXXXXX