XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXX XXXXXXXXX
    XXXXX
        XXX
            XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXX X XXXXXX XXXXXXXX XXXXX X XXXXX X XXX X XXXXXX XXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXXX XX XXXXXXX X XXXXXXXX XXXXXXXXX XXX XXXX X XXX XXXXXXXX XXXXXXXXXXXXXX
                X XX XXXXX XXXXXXXX X XX XXX XXXXXXXXX XXXX XXXXXX XXX XX XXXXXXXX XXX XXXXXXXX XX XXXXXX XXX XXXXX XX XXXXX XXXX X XXXXXXX XXXX XX XXXXXX XXXXXX X XXXXXXX XXXXXXXX XXXXXXXXXX X XXX XXXXX XXX XXXXXXXXX X XXXXXXX XXXX XXX X XXXXXXXXXXX
                XXXXXXXX X XXXXX XX X XXXXXXX X XXXXXXXXX X XXX XXXXXXXX X XXXXXXXXXX XXX XXXXXXXXXXXXX X XXX XXXXXXXXXXXXX XXX XX X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXX XX X XXXXXXXXXXXX XXXXXXXXXX XXXXXXX XX X XX XXX X XXX XXXXXXXXXXXXXX X XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX X XXXXXX XXXXXX X XXXXXX XXX XXXXXXXXXX X XXXX XXXXX X XXXX XXXXXX XXXXX XXXXX X X XXX XX XXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
        XXXX
        XXXXXXX XXXXXXXXX
        XXX
            XXXXXXXXX XXXXXXXXXXXXXXX XXX XXXX XXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXX XX XXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXX XXXX XXXXXXXXXXX
        XXXX
    XXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXX XXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XX
            XXXXXXXXXXXXXXX XXXX
        XXX
        XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXX XXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XX
            XXXXXXXXXXXXXXX XXXX
        XXX
    XXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX