XXXXXXXXX XXXXX

XXXXXX
    XXXX XXXXXX XXXXXXXXX XXXXXXX XXX XXXXXX XX XXX XX XXXX XXXX XXXXXX XXX XXXX XXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
        XXXX X
            XXXXXXXX XX
            XXXXXXX XX
            XXXXXXXXXXXXXXXXX XXXXXX
        X
        
        XXXXXX X
            XXXXXX XXXXXX
            XXXXXXX XXXXXX
        X
    XXXXXXXX
    XXXXXXXX
        XXXXXXXX XXXXXXXXX
        X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
        XXXXXXXXXXXXXXX X XXXXXXXXXX
        X
            XXXXXXX
            X
                XXX XXXXXXXXXX
            XXX
        XX
        XXXXXXXXXXXXXXXX X XXXXXXXXXXX XX
        X
            XXXXXXX
            X
                XXX XXXXXXXXXXXX
                XX XX
                XX X
            XXX
        XX
    XXXXXXXXX
XXXXXXX

XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
XXXXXXX