XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXXX XXXXXX XXXX XXXXXX XXXXXXXXXX
        XXXXXXXXXX XXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX X XXXXXXXXX XXX XXXX XXXXX XXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX XXXXXXXX X X XXXXXX XXXX XXXXXX XXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXX X XXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
            X XX X XXX XXXXXXXXXXXXXXXX XXXXX X X
            XXXXXXXXXXXXX X XX XXXXXXXXXXXXXXX X XXXXX
                XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXX X XXXXXXXXX X X XXXXXXXXXXXXXXXXX X XX X
                    XXXXXXXXXXXXX XXXXXXXXXXXX XXXX X XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XX
            XXXXXXXX XX
            XXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXXX
        XXX
    XXXXXXXXX
    XXXX
    XXXXXXXXX XXXX XXXX XXXXXXX XXXXXX XXXXXX X
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX