XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX X XXXX XX X XXXX XXXXXXXXX XXXXX XXXXX X XXXXX XXXXXXXX XXXXXXX XXXX X XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX X XXXXXXXX XXX X XXXXXXX XXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXX XXX XXXXXX XXX X XXXXXXXXXXXXXXXXXXXX X XXXXX XXXXX XXXXXX XXX XXXX XXXXXXXXXX
            XXXXXX X XXXXXXXXXXXXX XXXXX X X XXXXX XXXXX XXXX X XXXXXXXXXXXXXX X XXXX XXXXXXX X XXXX XXXXXXXXX X XXX XXX XXXXXX XX XXX XXXXXXX XXXX XX XXXXXXX XXXX XXXXX XXXXX XXXXXXXXXXXXXXX XX X XXXXXXXXXX XX X XXXXXXXX XXXXXXXXXXXXXX XX X XXXXXXXXXX
            XX X XXXXXXXX XXXXXXXXX XXXX X X XXXXXXXXX XXXXXXXXX XXX XX X X XXXX XXXXXX XXX XX XXXX XXXXXX XXXXXX XXXXX X X XXXXXXXX XXXXXXX X XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXX
            X
                XXXXX XXXXXX
            XX
            XXXXXXXXXXXX XXXX
        XXX
    XXXXXXXXX
    XXXXXXX XXXX XXXXXXXXX
    XXX XXXXXXX XX XXXXXX XXXXXXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX