XXXXXXXX
    XX XXXXXXX XXXX XXX XXXXXXXXXXX
    XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX
    X
        XXX XXX X XXXXXXXXX
        XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
XXXXXXXXX