XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXXXXXX XXXX XX XX XXXXXXXXXX XXXX XXXXXX XXXXX XXXXXXXXX XX XXXXX XXXXXXX XXXX X X X XX XXX XXXXXXXXX XXXXXX XXX XXXXX XXX XXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXXXXXXXX XXX XXX XXXX XXXXX XXX XXXXXXXXX X XXX XXXXXX XX XXXXXXXXXXXXXXXXXXX
        X XX XXXX XX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXX XXX XX X XX XXXXXX X XX XX XXX XXX XXX XXXXX XXXXXX XXXX XX XXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXX X X XXXXXXXXX X XX XX X XXXXXXXXXXXXXXXXXX XXX XXX XX XXXX XX X XXXXXXXXXXXXXXXXXX
        XXX XXX XX XXXX XX X XXXXXXXXXXXXXXXXXX XXX XXX XX XXXX XX XXXXXXXXXXX XXXXX XXXXXX XX XXXX XX XX XXXXX X XXXXX XXXXX X XXXXXXX XXXX X XXXXXXXXXXXXXXXXXX XX XXXXXXXX XX XX XXXXXXXXXX XXX XXXXXX X X X X X XXXXXXXXX XX XXX XX XXX XXX XXXXX XXXXXX
        XX XXXX X XXXXXXXX XXXX XXXX X XXXXXXXXXXXXXXXXXXXX XXX XXXXXX XX XXXXXXX X XXX X XX XXXXXXXXX XX XXXXXXXXXXXXXXXX XXXXXXX XXX X X XXXXXXXXXXX
    XXXXXXXX
        XXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
        XXX
    XXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXXXXXXX