# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_Facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(blank=True, max_length=256, null=True, verbose_name='Secret Key')),
            ],
            options={
                'verbose_name_plural': 'Apps Facebook',
            },
        ),
        migrations.CreateModel(
            name='App_Google',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(blank=True, max_length=256, null=True, verbose_name='Secret Key')),
            ],
            options={
                'verbose_name_plural': 'Apps Google',
            },
        ),
        migrations.CreateModel(
            name='App_Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(blank=True, max_length=256, null=True, verbose_name='Secret Key')),
            ],
            options={
                'verbose_name_plural': 'Apps Instagram',
            },
        ),
        migrations.CreateModel(
            name='App_Linkedin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(blank=True, max_length=256, null=True, verbose_name='Secret Key')),
            ],
            options={
                'verbose_name_plural': 'Apps Linkedin',
            },
        ),
        migrations.CreateModel(
            name='App_Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=32, null=True, verbose_name='Nombre')),
                ('consumer_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Consumer Key')),
                ('consumer_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Consumer Secret')),
                ('callback_url', models.URLField(blank=True, max_length=128, null=True, verbose_name='Callback URL')),
                ('owner', models.CharField(blank=True, max_length=64, null=True, verbose_name='Owner')),
                ('owner_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='Owner ID')),
                ('en_uso', models.BooleanField(default=False, verbose_name='En uso')),
            ],
            options={
                'verbose_name_plural': 'Apps Twitter',
            },
        ),
        migrations.CreateModel(
            name='Conector_Facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=256, null=True, verbose_name='Token')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Conectores Facebook',
            },
        ),
        migrations.CreateModel(
            name='Conector_Google',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=256, null=True, verbose_name='Token')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Conectores Google',
            },
        ),
        migrations.CreateModel(
            name='Conector_Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=256, null=True, verbose_name='Token')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Conectores Instagram',
            },
        ),
        migrations.CreateModel(
            name='Conector_Linkedin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=256, null=True, verbose_name='Token')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Conectores Linkedin',
            },
        ),
        migrations.CreateModel(
            name='Conector_Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Access Token')),
                ('access_token_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Access Token Secret')),
                ('token', models.CharField(blank=True, max_length=256, null=True, verbose_name='Token')),
                ('usuario_twitter', models.CharField(blank=True, max_length=64, null=True, verbose_name='Usuario de Twitter')),
                ('fecha', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('app_twitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.App_Twitter')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Conectores Twitter',
            },
        ),
    ]
