XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXX XXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXX
            XXXX XXXX XX X XXXXXXX XXX

            XXXXXX
                XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXX
                    XX X
                        XXXXXXXXXXXX XXXXX XXXXX
                        XXXXXX XXXXX
                    X
                    
                    XXX X
                        XXXXXXXXXXX XXXXXX XXXXXXXXXXX
                    X
                    
                    XXXX X
                        XXXXXXXXXX XXXXX
                        XXXXXXX XXX XXX XXX XXXX
                    X
                XXXXXXXX
            XXXXXXX

            XXXXXX
                XXXXXXXXX XXXX XXXXXXXXXXXX
                XXXXXXXX
                    XXXXXXXX XXXXXXXXXXXX XXXXX
                    X
                        XX XXXXX XX XXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
                    X
                XXXXXXXXX
            XXXXXXX

            XXXXXXX
        XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XX XXXXXX XX XXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXX XXX
        XX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XX XXXX XXXX
        XXX XXXXXXXXX X X
            XXXXX XXXXXXXXXXXX
            XXXXXXXXXXXX X
            X
                XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXX
            XX
            X
                XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXX
            XX
        XX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXX
        XXX
    XXXXXXXXX
    XXXXXX XXXX XXXXX XXXX XXXXXXX XX XXX XXXX XXXXXXXXXXX XXX XXX XXXXXXXXXX
    XXXXX XXXXX XX XXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXX XX XXXX XX XXX XXXXXX XXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XX XXXXXX XX XXXXXX XXXX XX XXXXX XX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXX XX X XXXXXX XX XXXXXX XXXX XXXXXXX XXX XXXXXX XXXXX XXX XXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXX XXXXX XXXX XXXXXX XXXX XX XXXX XXXXX XX X
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XX XXX XXXX XXXX XXXXXX XX XXXX XXX XXX XXXXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXXXX XX XXX XXXX XXXX XXXXXX XXXXX XXX XXX XXXXXXXXXXXX
XXXXXXXXXX