XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXX X
        XXXXXXX XXX XXXXX XXXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXXXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX
                XXXXXXXXXXXXXX
                    XXXXXXXXXXXX X
                        XXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXX XXXXXXXX XX X
                                XXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXXXX XXXXXXXX X XXXXXXXX
                                        XXXXXXXXXXXXXX XXXXXXXX XXXXXXX X XXXXXXXX
                                            XXXXXXXXXXXXXX XXXXXXXX XXXX
                                                XXXXXXXXXXXXX X XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX
    XXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX