# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo_Verificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movil', models.CharField(max_length=16, verbose_name='Móvil')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Códigos de Verificación Twilio',
            },
        ),
        migrations.CreateModel(
            name='Solicitud_Verificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movil', models.CharField(max_length=16, verbose_name='Móvil')),
                ('fecha_hora_soilcitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de la Solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes de verificación Twilio',
            },
        ),
        migrations.CreateModel(
            name='Twilio_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='E-mail')),
                ('account', models.CharField(max_length=64, unique=True, verbose_name='Account')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('en_uso', models.BooleanField(default=False, verbose_name='En uso')),
            ],
            options={
                'verbose_name_plural': 'Clientes Twilio',
            },
        ),
        migrations.CreateModel(
            name='Twilio_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16, verbose_name='Número')),
                ('sid', models.CharField(max_length=255, verbose_name='SID')),
                ('en_uso', models.BooleanField(default=False, verbose_name='En uso')),
            ],
            options={
                'verbose_name_plural': 'Números de Twilio',
            },
        ),
    ]
