countries = {
	"AFGHANISTAN": {"codigo_iso_alfa2": "AF", "codigo_iso_alfa3": "AFG", "codigo_iso_numerico": "None", "moneda_codigo_iso": "AFN", "idioma_codigo": None, "prefijo_movil": "93", "union_europea": False},
	"AKROTIRI AND DHEKELIA": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"ALBANIA": {"codigo_iso_alfa2": "AL", "codigo_iso_alfa3": "ALB", "codigo_iso_numerico": "None", "moneda_codigo_iso": "ALL", "idioma_codigo": None, "prefijo_movil": "355", "union_europea": False},
	"ALGERIA": {"codigo_iso_alfa2": "DZ", "codigo_iso_alfa3": "DZA", "codigo_iso_numerico": "None", "moneda_codigo_iso": "DZD", "idioma_codigo": None, "prefijo_movil": "213", "union_europea": False},
	"AMERICAN SAMOA": {"codigo_iso_alfa2": "AS", "codigo_iso_alfa3": "ASM", "codigo_iso_numerico": "016", "moneda_codigo_iso": "USD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"ANDORRA": {"codigo_iso_alfa2": "AD", "codigo_iso_alfa3": "AND", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": "376", "union_europea": False},
	"ANGOLA": {"codigo_iso_alfa2": "AO", "codigo_iso_alfa3": "AGO", "codigo_iso_numerico": "None", "moneda_codigo_iso": "AOA", "idioma_codigo": None, "prefijo_movil": "244", "union_europea": False},
	"ANGUILLA": {"codigo_iso_alfa2": "AI", "codigo_iso_alfa3": "AIA", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XCD", "idioma_codigo": "EN", "prefijo_movil": "1264", "union_europea": False},
	"ANTIGUA AND BARBUDA": {"codigo_iso_alfa2": "AG", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XCD", "idioma_codigo": None, "prefijo_movil": "1268", "union_europea": False},
	"ARGENTINA": {"codigo_iso_alfa2": "AR", "codigo_iso_alfa3": "ARG", "codigo_iso_numerico": "None", "moneda_codigo_iso": "ARS", "idioma_codigo": "ES", "prefijo_movil": "54", "union_europea": False},
	"ARMENIA": {"codigo_iso_alfa2": "AM", "codigo_iso_alfa3": "ARM", "codigo_iso_numerico": "None", "moneda_codigo_iso": "AMD", "idioma_codigo": None, "prefijo_movil": "374", "union_europea": False},
	"ARUBA": {"codigo_iso_alfa2": "AW", "codigo_iso_alfa3": "ABW", "codigo_iso_numerico": "None", "moneda_codigo_iso": "AWG", "idioma_codigo": None, "prefijo_movil": "297", "union_europea": False},
	"AUSTRALIA": {"codigo_iso_alfa2": "AU", "codigo_iso_alfa3": "AUS", "codigo_iso_numerico": "None", "moneda_codigo_iso": "AUD", "idioma_codigo": "EN", "prefijo_movil": "61", "union_europea": False},
	"AUSTRIA": {"codigo_iso_alfa2": "AT", "codigo_iso_alfa3": "AUT", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": "DE", "prefijo_movil": "43", "union_europea": True},
	"AZERBAIJAN": {"codigo_iso_alfa2": "AZ", "codigo_iso_alfa3": "AZE", "codigo_iso_numerico": "None", "moneda_codigo_iso": "AZN", "idioma_codigo": None, "prefijo_movil": "994", "union_europea": False},
	"BAHAMAS": {"codigo_iso_alfa2": "BS", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "BSD", "idioma_codigo": None, "prefijo_movil": "1242", "union_europea": False},
	"BAHRAIN": {"codigo_iso_alfa2": "BH", "codigo_iso_alfa3": "BHR", "codigo_iso_numerico": "None", "moneda_codigo_iso": "BHD", "idioma_codigo": None, "prefijo_movil": "973", "union_europea": False},
	"BANGLADESH": {"codigo_iso_alfa2": "BD", "codigo_iso_alfa3": "BGD", "codigo_iso_numerico": "None", "moneda_codigo_iso": "BDT", "idioma_codigo": None, "prefijo_movil": "880", "union_europea": False},
	"BARBADOS": {"codigo_iso_alfa2": "BB", "codigo_iso_alfa3": "BRB", "codigo_iso_numerico": "None", "moneda_codigo_iso": "BBD", "idioma_codigo": "EN", "prefijo_movil": "1246", "union_europea": False},
	"BELARUS": {"codigo_iso_alfa2": "BY", "codigo_iso_alfa3": "BLR", "codigo_iso_numerico": "None", "moneda_codigo_iso": "BYR", "idioma_codigo": None, "prefijo_movil": "375", "union_europea": False},
	"BELGIUM": {"codigo_iso_alfa2": "BE", "codigo_iso_alfa3": "BEL", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": "32", "union_europea": True},
	"BELIZE": {"codigo_iso_alfa2": "BZ", "codigo_iso_alfa3": "BLZ", "codigo_iso_numerico": "None", "moneda_codigo_iso": "BZD", "idioma_codigo": "EN", "prefijo_movil": "501", "union_europea": False},
	"BENIN": {"codigo_iso_alfa2": "BJ", "codigo_iso_alfa3": "BEN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XOF", "idioma_codigo": "FR", "prefijo_movil": "229", "union_europea": False},
	"BERMUDA": {"codigo_iso_alfa2": "BM", "codigo_iso_alfa3": "BMU", "codigo_iso_numerico": "None", "moneda_codigo_iso": "BMD", "idioma_codigo": "EN", "prefijo_movil": "1441", "union_europea": False},
	"BHUTAN": {"codigo_iso_alfa2": "BT", "codigo_iso_alfa3": "BTN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "BTN", "idioma_codigo": None, "prefijo_movil": "975", "union_europea": False},
	"BOLIVIA (PLURINATIONAL STATE OF)": {"codigo_iso_alfa2": "BO", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "BOV", "idioma_codigo": None, "prefijo_movil": "591", "union_europea": False},
	"BOSNIA AND HERZEGOVINA": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "BAM", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"BOTSWANA": {"codigo_iso_alfa2": "BW", "codigo_iso_alfa3": "BWA", "codigo_iso_numerico": "None", "moneda_codigo_iso": "BWP", "idioma_codigo": "EN", "prefijo_movil": "267", "union_europea": False},
	"BOUVET ISLAND": {"codigo_iso_alfa2": "BV", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "NOK", "idioma_codigo": None, "prefijo_movil": "47", "union_europea": False},
	"BRAZIL": {"codigo_iso_alfa2": "BR", "codigo_iso_alfa3": "BRA", "codigo_iso_numerico": "None", "moneda_codigo_iso": "BRL", "idioma_codigo": None, "prefijo_movil": "55", "union_europea": False},
	"BRITISH INDIAN OCEAN TERRITORY": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "USD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"BRUNEI DARUSSALAM": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "BND", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"BULGARIA": {"codigo_iso_alfa2": "BG", "codigo_iso_alfa3": "BGR", "codigo_iso_numerico": "None", "moneda_codigo_iso": "BGN", "idioma_codigo": None, "prefijo_movil": "359", "union_europea": True},
	"BURKINA FASO": {"codigo_iso_alfa2": "BF", "codigo_iso_alfa3": "BFA", "codigo_iso_numerico": "854", "moneda_codigo_iso": "XOF", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"BURUNDI": {"codigo_iso_alfa2": "BI", "codigo_iso_alfa3": "BDI", "codigo_iso_numerico": "None", "moneda_codigo_iso": "BIF", "idioma_codigo": "FR", "prefijo_movil": "257", "union_europea": False},
	"CAIMAN ISLANDS": {"codigo_iso_alfa2": "KY", "codigo_iso_alfa3": "CYM", "codigo_iso_numerico": "136", "moneda_codigo_iso": None, "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"CAMBODIA": {"codigo_iso_alfa2": "KH", "codigo_iso_alfa3": "KHM", "codigo_iso_numerico": "None", "moneda_codigo_iso": "KHR", "idioma_codigo": None, "prefijo_movil": "855", "union_europea": False},
	"CAMEROON": {"codigo_iso_alfa2": "CM", "codigo_iso_alfa3": "CMR", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XAF", "idioma_codigo": "EN", "prefijo_movil": "237", "union_europea": False},
	"CANADA": {"codigo_iso_alfa2": "CA", "codigo_iso_alfa3": "CAN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "CAD", "idioma_codigo": "EN", "prefijo_movil": "1", "union_europea": False},
	"CAPE VERDE": {"codigo_iso_alfa2": "CV", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "CVE", "idioma_codigo": None, "prefijo_movil": "238", "union_europea": False},
	"CAYMAN ISLANDS": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "KYD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"CENTRAL AFRICAN REPUBLIC": {"codigo_iso_alfa2": "CF", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XAF", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"CHAD": {"codigo_iso_alfa2": "TD", "codigo_iso_alfa3": "TCD", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XAF", "idioma_codigo": "FR", "prefijo_movil": "235", "union_europea": False},
	"CHILE": {"codigo_iso_alfa2": "CL", "codigo_iso_alfa3": "CHL", "codigo_iso_numerico": "None", "moneda_codigo_iso": "CLP", "idioma_codigo": "ES", "prefijo_movil": "56", "union_europea": False},
	"CHINA": {"codigo_iso_alfa2": "CN", "codigo_iso_alfa3": "CHN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "CNY", "idioma_codigo": None, "prefijo_movil": "86", "union_europea": False},
	"CHRISTMAS ISLAND": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "AUD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"COCOS (KEELING) ISLANDS": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "AUD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"COLOMBIA": {"codigo_iso_alfa2": "CO", "codigo_iso_alfa3": "COL", "codigo_iso_numerico": "None", "moneda_codigo_iso": "COU", "idioma_codigo": "ES", "prefijo_movil": "57", "union_europea": False},
	"COMOROS": {"codigo_iso_alfa2": "KM", "codigo_iso_alfa3": "COM", "codigo_iso_numerico": "None", "moneda_codigo_iso": "KMF", "idioma_codigo": None, "prefijo_movil": "269", "union_europea": False},
	"COOK ISLANDS": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "NZD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"COSTA RICA": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "CRC", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"COTE D'IVOIRE": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XOF", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"CROATIA": {"codigo_iso_alfa2": "HR", "codigo_iso_alfa3": "HRV", "codigo_iso_numerico": "None", "moneda_codigo_iso": "HRK", "idioma_codigo": None, "prefijo_movil": "385", "union_europea": True},
	"CUBA": {"codigo_iso_alfa2": "CU", "codigo_iso_alfa3": "CUB", "codigo_iso_numerico": "192", "moneda_codigo_iso": "CUC", "idioma_codigo": "ES", "prefijo_movil": "53", "union_europea": False},
	"CYPRUS": {"codigo_iso_alfa2": "CY", "codigo_iso_alfa3": "CYP", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": "357", "union_europea": True},
	"CZECH REPUBLIC": {"codigo_iso_alfa2": "CZ", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "CZK", "idioma_codigo": None, "prefijo_movil": None, "union_europea": True},
	"DEMOCRATIC REPUBLIC OF CONGO": {"codigo_iso_alfa2": "CD", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "CDF", "idioma_codigo": None, "prefijo_movil": "242", "union_europea": False},
	"DENMARK": {"codigo_iso_alfa2": "DK", "codigo_iso_alfa3": "DNK", "codigo_iso_numerico": "None", "moneda_codigo_iso": "DKK", "idioma_codigo": None, "prefijo_movil": "45", "union_europea": True},
	"DJIBOUTI": {"codigo_iso_alfa2": "DJ", "codigo_iso_alfa3": "DJI", "codigo_iso_numerico": "None", "moneda_codigo_iso": "DJF", "idioma_codigo": "FR", "prefijo_movil": "253", "union_europea": False},
	"DOMINICA": {"codigo_iso_alfa2": "DM", "codigo_iso_alfa3": "DMA", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XCD", "idioma_codigo": "EN", "prefijo_movil": "1767", "union_europea": False},
	"DOMINICAN REPUBLIC": {"codigo_iso_alfa2": "DO", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "DOP", "idioma_codigo": None, "prefijo_movil": "1", "union_europea": False},
	"ECUADOR": {"codigo_iso_alfa2": "EC", "codigo_iso_alfa3": "ECU", "codigo_iso_numerico": "None", "moneda_codigo_iso": "USD", "idioma_codigo": "ES", "prefijo_movil": "593", "union_europea": False},
	"EGYPT": {"codigo_iso_alfa2": "EG", "codigo_iso_alfa3": "EGY", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EGP", "idioma_codigo": None, "prefijo_movil": "20", "union_europea": False},
	"EL SALVADOR": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "SVC", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"EQUATORIAL GUINEA": {"codigo_iso_alfa2": "GQ", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XAF", "idioma_codigo": None, "prefijo_movil": "240", "union_europea": False},
	"ERITREA": {"codigo_iso_alfa2": "ER", "codigo_iso_alfa3": "ERI", "codigo_iso_numerico": "None", "moneda_codigo_iso": "ERN", "idioma_codigo": None, "prefijo_movil": "291", "union_europea": False},
	"ESTONIA": {"codigo_iso_alfa2": "EE", "codigo_iso_alfa3": "EST", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": "372", "union_europea": True},
	"ETHIOPIA": {"codigo_iso_alfa2": "ET", "codigo_iso_alfa3": "ETH", "codigo_iso_numerico": "None", "moneda_codigo_iso": "ETB", "idioma_codigo": None, "prefijo_movil": "251", "union_europea": False},
	"FALKLAND ISLANDS (MALVINAS)": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "FKP", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"FAROE ISLANDS": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "DKK", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"FIJI": {"codigo_iso_alfa2": "FJ", "codigo_iso_alfa3": "FJI", "codigo_iso_numerico": "None", "moneda_codigo_iso": "FJD", "idioma_codigo": "EN", "prefijo_movil": "679", "union_europea": False},
	"FINLAND": {"codigo_iso_alfa2": "FI", "codigo_iso_alfa3": "FIN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": "358", "union_europea": True},
	"FRANCE": {"codigo_iso_alfa2": "FR", "codigo_iso_alfa3": "FRA", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": "FR", "prefijo_movil": "33", "union_europea": True},
	"FRENCH POLYNESIA": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XPF", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"GABON": {"codigo_iso_alfa2": "GA", "codigo_iso_alfa3": "GAB", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XAF", "idioma_codigo": "FR", "prefijo_movil": "241", "union_europea": False},
	"GAMBIA": {"codigo_iso_alfa2": "GM", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "GMD", "idioma_codigo": None, "prefijo_movil": "220", "union_europea": False},
	"GEORGIA": {"codigo_iso_alfa2": "GE", "codigo_iso_alfa3": "GEO", "codigo_iso_numerico": "None", "moneda_codigo_iso": "GEL", "idioma_codigo": None, "prefijo_movil": "995", "union_europea": False},
	"GERMANY": {"codigo_iso_alfa2": "DE", "codigo_iso_alfa3": "DEU", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": "DE", "prefijo_movil": "49", "union_europea": True},
	"GHANA": {"codigo_iso_alfa2": "GH", "codigo_iso_alfa3": "GHA", "codigo_iso_numerico": "None", "moneda_codigo_iso": "GHS", "idioma_codigo": "EN", "prefijo_movil": "233", "union_europea": False},
	"GIBRALTAR": {"codigo_iso_alfa2": "GI", "codigo_iso_alfa3": "GIB", "codigo_iso_numerico": "None", "moneda_codigo_iso": "GIP", "idioma_codigo": "EN", "prefijo_movil": "350", "union_europea": False},
	"GREECE": {"codigo_iso_alfa2": "GR", "codigo_iso_alfa3": "GRC", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": "30", "union_europea": True},
	"GREENLAND": {"codigo_iso_alfa2": "GL", "codigo_iso_alfa3": "GRL", "codigo_iso_numerico": "None", "moneda_codigo_iso": "DKK", "idioma_codigo": None, "prefijo_movil": "299", "union_europea": False},
	"GRENADA": {"codigo_iso_alfa2": "GD", "codigo_iso_alfa3": "GRD", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XCD", "idioma_codigo": "EN", "prefijo_movil": "1473", "union_europea": False},
	"GUADELOUPE": {"codigo_iso_alfa2": "GP", "codigo_iso_alfa3": "GLP", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": "FR", "prefijo_movil": "590", "union_europea": False},
	"GUAM": {"codigo_iso_alfa2": "GU", "codigo_iso_alfa3": "GUM", "codigo_iso_numerico": "None", "moneda_codigo_iso": "USD", "idioma_codigo": "EN", "prefijo_movil": "1671", "union_europea": False},
	"GUATEMALA": {"codigo_iso_alfa2": "GT", "codigo_iso_alfa3": "GTM", "codigo_iso_numerico": "None", "moneda_codigo_iso": "GTQ", "idioma_codigo": "ES", "prefijo_movil": "502", "union_europea": False},
	"GUINEA": {"codigo_iso_alfa2": "GN", "codigo_iso_alfa3": "GIN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "GNF", "idioma_codigo": "FR", "prefijo_movil": "224", "union_europea": False},
	"GUINEA-BISSAU": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XOF", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"GUYANA": {"codigo_iso_alfa2": "GY", "codigo_iso_alfa3": "GUY", "codigo_iso_numerico": "None", "moneda_codigo_iso": "GYD", "idioma_codigo": "EN", "prefijo_movil": "592", "union_europea": False},
	"HAITI": {"codigo_iso_alfa2": "HT", "codigo_iso_alfa3": "HTI", "codigo_iso_numerico": "None", "moneda_codigo_iso": "HTG", "idioma_codigo": "FR", "prefijo_movil": "509", "union_europea": False},
	"HEARD ISLAND AND MCDONALD ISLANDS": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "AUD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"HONDURAS": {"codigo_iso_alfa2": "HN", "codigo_iso_alfa3": "HND", "codigo_iso_numerico": "None", "moneda_codigo_iso": "HNL", "idioma_codigo": "ES", "prefijo_movil": "504", "union_europea": False},
	"HONG KONG": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "HKD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"HUNGARY": {"codigo_iso_alfa2": "HU", "codigo_iso_alfa3": "HUN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "HUF", "idioma_codigo": None, "prefijo_movil": "36", "union_europea": True},
	"ICELAND": {"codigo_iso_alfa2": "IS", "codigo_iso_alfa3": "ISL", "codigo_iso_numerico": "None", "moneda_codigo_iso": "ISK", "idioma_codigo": None, "prefijo_movil": "354", "union_europea": False},
	"INDIA": {"codigo_iso_alfa2": "IN", "codigo_iso_alfa3": "IND", "codigo_iso_numerico": "None", "moneda_codigo_iso": "INR", "idioma_codigo": None, "prefijo_movil": "91", "union_europea": False},
	"INDONESIA": {"codigo_iso_alfa2": "ID", "codigo_iso_alfa3": "IDN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "IDR", "idioma_codigo": None, "prefijo_movil": "62", "union_europea": False},
	"IRAN": {"codigo_iso_alfa2": "IR", "codigo_iso_alfa3": "IRN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "IRR", "idioma_codigo": None, "prefijo_movil": "98", "union_europea": False},
	"IRAQ": {"codigo_iso_alfa2": "IQ", "codigo_iso_alfa3": "IRQ", "codigo_iso_numerico": "None", "moneda_codigo_iso": "IQD", "idioma_codigo": None, "prefijo_movil": "964", "union_europea": False},
	"IRELAND": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": None, "union_europea": True},
	"ISLE OF MAN": {"codigo_iso_alfa2": "IM", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "IMP", "idioma_codigo": None, "prefijo_movil": "44", "union_europea": False},
	"ISRAEL": {"codigo_iso_alfa2": "IL", "codigo_iso_alfa3": "ISR", "codigo_iso_numerico": "None", "moneda_codigo_iso": "ILS", "idioma_codigo": None, "prefijo_movil": "972", "union_europea": False},
	"ITALY": {"codigo_iso_alfa2": "IT", "codigo_iso_alfa3": "ITA", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": "IT", "prefijo_movil": "39", "union_europea": True},
	"JAMAICA": {"codigo_iso_alfa2": "JM", "codigo_iso_alfa3": "JAM", "codigo_iso_numerico": "None", "moneda_codigo_iso": "JMD", "idioma_codigo": "EN", "prefijo_movil": "1876", "union_europea": False},
	"JAPAN": {"codigo_iso_alfa2": "JP", "codigo_iso_alfa3": "JPN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "JPY", "idioma_codigo": None, "prefijo_movil": "81", "union_europea": False},
	"JORDAN": {"codigo_iso_alfa2": "JO", "codigo_iso_alfa3": "JOR", "codigo_iso_numerico": "None", "moneda_codigo_iso": "JOD", "idioma_codigo": None, "prefijo_movil": "962", "union_europea": False},
	"KAZAKHSTAN": {"codigo_iso_alfa2": "KZ", "codigo_iso_alfa3": "KAZ", "codigo_iso_numerico": "None", "moneda_codigo_iso": "KZT", "idioma_codigo": None, "prefijo_movil": "76", "union_europea": False},
	"KENYA": {"codigo_iso_alfa2": "KE", "codigo_iso_alfa3": "KEN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "KES", "idioma_codigo": "EN", "prefijo_movil": "254", "union_europea": False},
	"KIRIBATI": {"codigo_iso_alfa2": "KI", "codigo_iso_alfa3": "KIR", "codigo_iso_numerico": "None", "moneda_codigo_iso": "AUD", "idioma_codigo": "EN", "prefijo_movil": "686", "union_europea": False},
	"KOREA": {"codigo_iso_alfa2": "KR", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "KRW", "idioma_codigo": None, "prefijo_movil": "82", "union_europea": False},
	"KOSOVO": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"KUWAIT": {"codigo_iso_alfa2": "KW", "codigo_iso_alfa3": "KWT", "codigo_iso_numerico": "None", "moneda_codigo_iso": "KWD", "idioma_codigo": None, "prefijo_movil": "965", "union_europea": False},
	"KYRGYZSTAN": {"codigo_iso_alfa2": "KG", "codigo_iso_alfa3": "KGZ", "codigo_iso_numerico": "None", "moneda_codigo_iso": "KGS", "idioma_codigo": None, "prefijo_movil": "996", "union_europea": False},
	"LAO PEOPLES DEMOCRATIC REPUBLIC": {"codigo_iso_alfa2": "LA", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "LAK", "idioma_codigo": None, "prefijo_movil": "856", "union_europea": False},
	"LATVIA": {"codigo_iso_alfa2": "LV", "codigo_iso_alfa3": "LVA", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": "371", "union_europea": True},
	"LEBANON": {"codigo_iso_alfa2": "LB", "codigo_iso_alfa3": "LBN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "LBP", "idioma_codigo": None, "prefijo_movil": "961", "union_europea": False},
	"LESOTHO": {"codigo_iso_alfa2": "LS", "codigo_iso_alfa3": "LSO", "codigo_iso_numerico": "None", "moneda_codigo_iso": "LSL", "idioma_codigo": "EN", "prefijo_movil": "266", "union_europea": False},
	"LIBERIA": {"codigo_iso_alfa2": "LR", "codigo_iso_alfa3": "LBR", "codigo_iso_numerico": "None", "moneda_codigo_iso": "LRD", "idioma_codigo": "EN", "prefijo_movil": "231", "union_europea": False},
	"LIBYAN ARAB JAMAHIRIYA": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "LYD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"LIECHTENSTEIN": {"codigo_iso_alfa2": "LI", "codigo_iso_alfa3": "LIE", "codigo_iso_numerico": "None", "moneda_codigo_iso": "CHF", "idioma_codigo": "DE", "prefijo_movil": "423", "union_europea": False},
	"LITHUANIA": {"codigo_iso_alfa2": "LT", "codigo_iso_alfa3": "LTU", "codigo_iso_numerico": "None", "moneda_codigo_iso": "LTL", "idioma_codigo": None, "prefijo_movil": "370", "union_europea": True},
	"LUXEMBOURG": {"codigo_iso_alfa2": "LU", "codigo_iso_alfa3": "LUX", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": "FR", "prefijo_movil": "352", "union_europea": True},
	"MACAO": {"codigo_iso_alfa2": "MO", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "MOP", "idioma_codigo": None, "prefijo_movil": "853", "union_europea": False},
	"MACEDONIA": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "MKD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"MADAGASCAR": {"codigo_iso_alfa2": "MG", "codigo_iso_alfa3": "MDG", "codigo_iso_numerico": "None", "moneda_codigo_iso": "MGA", "idioma_codigo": "FR", "prefijo_movil": "261", "union_europea": False},
	"MALAWI": {"codigo_iso_alfa2": "MW", "codigo_iso_alfa3": "MWI", "codigo_iso_numerico": "None", "moneda_codigo_iso": "MWK", "idioma_codigo": "EN", "prefijo_movil": "265", "union_europea": False},
	"MALAYSIA": {"codigo_iso_alfa2": "MY", "codigo_iso_alfa3": "MYS", "codigo_iso_numerico": "None", "moneda_codigo_iso": "MYR", "idioma_codigo": None, "prefijo_movil": "60", "union_europea": False},
	"MALDIVES": {"codigo_iso_alfa2": "MV", "codigo_iso_alfa3": "MDV", "codigo_iso_numerico": "None", "moneda_codigo_iso": "MVR", "idioma_codigo": None, "prefijo_movil": "960", "union_europea": False},
	"MALI": {"codigo_iso_alfa2": "ML", "codigo_iso_alfa3": "MLI", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XOF", "idioma_codigo": "FR", "prefijo_movil": "223", "union_europea": False},
	"MALTA": {"codigo_iso_alfa2": "MT", "codigo_iso_alfa3": "MLT", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": "356", "union_europea": True},
	"MARSHALL ISLANDS": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "USD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"MARTINIQUE": {"codigo_iso_alfa2": "MQ", "codigo_iso_alfa3": "MTQ", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": "FR", "prefijo_movil": "596", "union_europea": False},
	"MAURITANIA": {"codigo_iso_alfa2": "MR", "codigo_iso_alfa3": "MRT", "codigo_iso_numerico": "None", "moneda_codigo_iso": "MRO", "idioma_codigo": None, "prefijo_movil": "222", "union_europea": False},
	"MAURITIUS": {"codigo_iso_alfa2": "MU", "codigo_iso_alfa3": "MUS", "codigo_iso_numerico": "None", "moneda_codigo_iso": "MUR", "idioma_codigo": "EN", "prefijo_movil": "230", "union_europea": False},
	"MAYOTTE": {"codigo_iso_alfa2": "YT", "codigo_iso_alfa3": "MYT", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": "FR", "prefijo_movil": "262", "union_europea": False},
	"MEXICO": {"codigo_iso_alfa2": "MX", "codigo_iso_alfa3": "MEX", "codigo_iso_numerico": "None", "moneda_codigo_iso": "MXV", "idioma_codigo": "ES", "prefijo_movil": "52", "union_europea": False},
	"MICRONESIA": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "USD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"MOLDOVA": {"codigo_iso_alfa2": "MD", "codigo_iso_alfa3": "MDA", "codigo_iso_numerico": "None", "moneda_codigo_iso": "MDL", "idioma_codigo": None, "prefijo_movil": "373", "union_europea": False},
	"MONACO": {"codigo_iso_alfa2": "MC", "codigo_iso_alfa3": "MCO", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": "FR", "prefijo_movil": "377", "union_europea": False},
	"MONGOLIA": {"codigo_iso_alfa2": "MN", "codigo_iso_alfa3": "MNG", "codigo_iso_numerico": "None", "moneda_codigo_iso": "MNT", "idioma_codigo": None, "prefijo_movil": "976", "union_europea": False},
	"MONTENEGRO": {"codigo_iso_alfa2": "ME", "codigo_iso_alfa3": "MNE", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": "382", "union_europea": False},
	"MONTSERRAT": {"codigo_iso_alfa2": "MS", "codigo_iso_alfa3": "MSR", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XCD", "idioma_codigo": "EN", "prefijo_movil": "1664", "union_europea": False},
	"MOROCCO": {"codigo_iso_alfa2": "MA", "codigo_iso_alfa3": "MAR", "codigo_iso_numerico": "None", "moneda_codigo_iso": "MAD", "idioma_codigo": None, "prefijo_movil": "212", "union_europea": False},
	"MOZAMBIQUE": {"codigo_iso_alfa2": "MZ", "codigo_iso_alfa3": "MOZ", "codigo_iso_numerico": "None", "moneda_codigo_iso": "MZN", "idioma_codigo": None, "prefijo_movil": "258", "union_europea": False},
	"MYANMAR": {"codigo_iso_alfa2": "MM", "codigo_iso_alfa3": "MMR", "codigo_iso_numerico": "None", "moneda_codigo_iso": "MMK", "idioma_codigo": None, "prefijo_movil": "95", "union_europea": False},
	"NAMIBIA": {"codigo_iso_alfa2": "NA", "codigo_iso_alfa3": "NAM", "codigo_iso_numerico": "None", "moneda_codigo_iso": "NAD", "idioma_codigo": "EN", "prefijo_movil": "264", "union_europea": False},
	"NAURU": {"codigo_iso_alfa2": "NR", "codigo_iso_alfa3": "NRU", "codigo_iso_numerico": "None", "moneda_codigo_iso": "AUD", "idioma_codigo": "EN", "prefijo_movil": "674", "union_europea": False},
	"NEPAL": {"codigo_iso_alfa2": "NP", "codigo_iso_alfa3": "NPL", "codigo_iso_numerico": "None", "moneda_codigo_iso": "NPR", "idioma_codigo": None, "prefijo_movil": "977", "union_europea": False},
	"NETHERLANDS": {"codigo_iso_alfa2": "NL", "codigo_iso_alfa3": "NLD", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": "31", "union_europea": True},
	"NETHERLANDS ANTILLES": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "ANG", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"NEW CALEDONIA": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XPF", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"NEW ZEALAND": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "NZD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"NICARAGUA": {"codigo_iso_alfa2": "NI", "codigo_iso_alfa3": "NIC", "codigo_iso_numerico": "None", "moneda_codigo_iso": "NIO", "idioma_codigo": "ES", "prefijo_movil": "505", "union_europea": False},
	"NIGER": {"codigo_iso_alfa2": "NE", "codigo_iso_alfa3": "NER", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XOF", "idioma_codigo": "FR", "prefijo_movil": "227", "union_europea": False},
	"NIGERIA": {"codigo_iso_alfa2": "NG", "codigo_iso_alfa3": "NGA", "codigo_iso_numerico": "None", "moneda_codigo_iso": "NGN", "idioma_codigo": "EN", "prefijo_movil": "234", "union_europea": False},
	"NIUE": {"codigo_iso_alfa2": "NU", "codigo_iso_alfa3": "NIU", "codigo_iso_numerico": "None", "moneda_codigo_iso": "NZD", "idioma_codigo": "EN", "prefijo_movil": "683", "union_europea": False},
	"NORFOLK ISLAND": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "AUD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"NORTHERN MARIANA ISLANDS": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "USD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"NORWAY": {"codigo_iso_alfa2": "NO", "codigo_iso_alfa3": "NOR", "codigo_iso_numerico": "None", "moneda_codigo_iso": "NOK", "idioma_codigo": None, "prefijo_movil": "47", "union_europea": False},
	"OMAN": {"codigo_iso_alfa2": "OM", "codigo_iso_alfa3": "OMN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "OMR", "idioma_codigo": None, "prefijo_movil": "968", "union_europea": False},
	"PAKISTAN": {"codigo_iso_alfa2": "PK", "codigo_iso_alfa3": "PAK", "codigo_iso_numerico": "None", "moneda_codigo_iso": "PKR", "idioma_codigo": "EN", "prefijo_movil": "92", "union_europea": False},
	"PALAU": {"codigo_iso_alfa2": "PW", "codigo_iso_alfa3": "PLW", "codigo_iso_numerico": "None", "moneda_codigo_iso": "USD", "idioma_codigo": "EN", "prefijo_movil": "680", "union_europea": False},
	"PANAMA": {"codigo_iso_alfa2": "PA", "codigo_iso_alfa3": "PAN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "PAB", "idioma_codigo": "ES", "prefijo_movil": "507", "union_europea": False},
	"PAPUA NEW GUINEA": {"codigo_iso_alfa2": "PG", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "PGK", "idioma_codigo": None, "prefijo_movil": "675", "union_europea": False},
	"PARAGUAY": {"codigo_iso_alfa2": "PY", "codigo_iso_alfa3": "PRY", "codigo_iso_numerico": "None", "moneda_codigo_iso": "PYG", "idioma_codigo": "ES", "prefijo_movil": "595", "union_europea": False},
	"PERU": {"codigo_iso_alfa2": "PE", "codigo_iso_alfa3": "PER", "codigo_iso_numerico": "None", "moneda_codigo_iso": "PEN", "idioma_codigo": "ES", "prefijo_movil": "51", "union_europea": False},
	"PHILIPPINES": {"codigo_iso_alfa2": "PH", "codigo_iso_alfa3": "PHL", "codigo_iso_numerico": "None", "moneda_codigo_iso": "PHP", "idioma_codigo": "EN", "prefijo_movil": "63", "union_europea": False},
	"PITCAIRN": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "NZD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"POLAND": {"codigo_iso_alfa2": "PL", "codigo_iso_alfa3": "POL", "codigo_iso_numerico": "None", "moneda_codigo_iso": "PLN", "idioma_codigo": None, "prefijo_movil": "48", "union_europea": True},
	"PORTUGAL": {"codigo_iso_alfa2": "PT", "codigo_iso_alfa3": "PRT", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": "351", "union_europea": True},
	"PUERTO RICO": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "USD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"QATAR": {"codigo_iso_alfa2": "QA", "codigo_iso_alfa3": "QAT", "codigo_iso_numerico": "None", "moneda_codigo_iso": "QAR", "idioma_codigo": None, "prefijo_movil": "974", "union_europea": False},
	"REPUBLIC OF THE CONGO": {"codigo_iso_alfa2": "CD", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XAF", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"RÉUNION": {"codigo_iso_alfa2": "RE", "codigo_iso_alfa3": "REU", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": "FR", "prefijo_movil": "262", "union_europea": False},
	"ROMANIA": {"codigo_iso_alfa2": "RO", "codigo_iso_alfa3": "ROU", "codigo_iso_numerico": "None", "moneda_codigo_iso": "RON", "idioma_codigo": None, "prefijo_movil": "40", "union_europea": True},
	"RUSSIAN FEDERATION": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "RUB", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"RWANDA": {"codigo_iso_alfa2": "RW", "codigo_iso_alfa3": "RWA", "codigo_iso_numerico": "None", "moneda_codigo_iso": "RWF", "idioma_codigo": None, "prefijo_movil": "250", "union_europea": False},
	"SAINT BARTHÉLEMY": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"SAINT HELENA": {"codigo_iso_alfa2": "SH", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "SHP", "idioma_codigo": None, "prefijo_movil": "290", "union_europea": False},
	"SAINT KITTS AND NEVIS": {"codigo_iso_alfa2": "KN", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XCD", "idioma_codigo": None, "prefijo_movil": "1869", "union_europea": False},
	"SAINT LUCIA": {"codigo_iso_alfa2": "LC", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XCD", "idioma_codigo": None, "prefijo_movil": "1758", "union_europea": False},
	"SAINT PIERRE AND MIQUELON": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"SAINT VINCENT AND THE GRENADINES": {"codigo_iso_alfa2": "VC", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XCD", "idioma_codigo": None, "prefijo_movil": "1784", "union_europea": False},
	"SAMOA": {"codigo_iso_alfa2": "WS", "codigo_iso_alfa3": "WSM", "codigo_iso_numerico": "None", "moneda_codigo_iso": "WST", "idioma_codigo": None, "prefijo_movil": "685", "union_europea": False},
	"SAN MARINO": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"SAO TOME AND PRINCIPE": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "STD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"SAUDI ARABIA": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "SAR", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"SENEGAL": {"codigo_iso_alfa2": "SN", "codigo_iso_alfa3": "SEN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XOF", "idioma_codigo": "FR", "prefijo_movil": "221", "union_europea": False},
	"SERBIA": {"codigo_iso_alfa2": "RS", "codigo_iso_alfa3": "SRB", "codigo_iso_numerico": "None", "moneda_codigo_iso": "RSD", "idioma_codigo": None, "prefijo_movil": "381", "union_europea": False},
	"SEYCHELLES": {"codigo_iso_alfa2": "SC", "codigo_iso_alfa3": "SYC", "codigo_iso_numerico": "None", "moneda_codigo_iso": "SCR", "idioma_codigo": "FR", "prefijo_movil": "248", "union_europea": False},
	"SIERRA LEONE": {"codigo_iso_alfa2": "SL", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "SLL", "idioma_codigo": None, "prefijo_movil": "232", "union_europea": False},
	"SINGAPORE": {"codigo_iso_alfa2": "SG", "codigo_iso_alfa3": "SGP", "codigo_iso_numerico": "None", "moneda_codigo_iso": "SGD", "idioma_codigo": "EN", "prefijo_movil": "65", "union_europea": False},
	"SLOVAKIA": {"codigo_iso_alfa2": "SK", "codigo_iso_alfa3": "SVK", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": "421", "union_europea": True},
	"SLOVENIA": {"codigo_iso_alfa2": "SI", "codigo_iso_alfa3": "SVN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": "386", "union_europea": True},
	"SOLOMON ISLANDS": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "SBD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"SOMALIA": {"codigo_iso_alfa2": "SO", "codigo_iso_alfa3": "SOM", "codigo_iso_numerico": "None", "moneda_codigo_iso": "SOS", "idioma_codigo": None, "prefijo_movil": "252", "union_europea": False},
	"SOUTH AFRICA": {"codigo_iso_alfa2": "ZA", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "ZAR", "idioma_codigo": None, "prefijo_movil": "27", "union_europea": False},
	"SOUTH SUDAN": {"codigo_iso_alfa2": "SS", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "SSP", "idioma_codigo": None, "prefijo_movil": "211", "union_europea": False},
	"SPAIN": {"codigo_iso_alfa2": "ES", "codigo_iso_alfa3": "ESP", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": "ES", "prefijo_movil": "34", "union_europea": True},
	"SRI LANKA": {"codigo_iso_alfa2": "LK", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "LKR", "idioma_codigo": None, "prefijo_movil": "94", "union_europea": False},
	"SUDAN": {"codigo_iso_alfa2": "SD", "codigo_iso_alfa3": "SDN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "SDG", "idioma_codigo": None, "prefijo_movil": "249", "union_europea": False},
	"SURINAME": {"codigo_iso_alfa2": "SR", "codigo_iso_alfa3": "SUR", "codigo_iso_numerico": "None", "moneda_codigo_iso": "SRD", "idioma_codigo": None, "prefijo_movil": "597", "union_europea": False},
	"SVALBARD AND JAN MAYEN": {"codigo_iso_alfa2": "SJ", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "NOK", "idioma_codigo": None, "prefijo_movil": "47", "union_europea": False},
	"SWAZILAND": {"codigo_iso_alfa2": "SZ", "codigo_iso_alfa3": "SWZ", "codigo_iso_numerico": "None", "moneda_codigo_iso": "SZL", "idioma_codigo": "EN", "prefijo_movil": "268", "union_europea": False},
	"SWEDEN": {"codigo_iso_alfa2": "SE", "codigo_iso_alfa3": "SWE", "codigo_iso_numerico": "None", "moneda_codigo_iso": "SEK", "idioma_codigo": None, "prefijo_movil": "46", "union_europea": True},
	"SWITZERLAND": {"codigo_iso_alfa2": "CH", "codigo_iso_alfa3": "CHE", "codigo_iso_numerico": "None", "moneda_codigo_iso": "CHE", "idioma_codigo": "DE", "prefijo_movil": "41", "union_europea": False},
	"SYRIAN ARAB REPUBLIC": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "SYP", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"TAIWAN": {"codigo_iso_alfa2": "TW", "codigo_iso_alfa3": "TWN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "TWD", "idioma_codigo": None, "prefijo_movil": "886", "union_europea": False},
	"TAJIKISTAN": {"codigo_iso_alfa2": "TJ", "codigo_iso_alfa3": "TJK", "codigo_iso_numerico": "None", "moneda_codigo_iso": "TJS", "idioma_codigo": None, "prefijo_movil": "992", "union_europea": False},
	"TANZANIA": {"codigo_iso_alfa2": "TZ", "codigo_iso_alfa3": "TZA", "codigo_iso_numerico": "None", "moneda_codigo_iso": "TZS", "idioma_codigo": None, "prefijo_movil": "255", "union_europea": False},
	"THAILAND": {"codigo_iso_alfa2": "TH", "codigo_iso_alfa3": "THA", "codigo_iso_numerico": "None", "moneda_codigo_iso": "THB", "idioma_codigo": None, "prefijo_movil": "66", "union_europea": False},
	"TIMOR-LESTE": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "USD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"TOGO": {"codigo_iso_alfa2": "TG", "codigo_iso_alfa3": "TGO", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XOF", "idioma_codigo": "FR", "prefijo_movil": "228", "union_europea": False},
	"TOKELAU": {"codigo_iso_alfa2": "TK", "codigo_iso_alfa3": "TKL", "codigo_iso_numerico": "None", "moneda_codigo_iso": "NZD", "idioma_codigo": "EN", "prefijo_movil": "690", "union_europea": False},
	"TONGA": {"codigo_iso_alfa2": "TO", "codigo_iso_alfa3": "TON", "codigo_iso_numerico": "None", "moneda_codigo_iso": "TOP", "idioma_codigo": "EN", "prefijo_movil": "676", "union_europea": False},
	"TRINIDAD AND TOBAGO": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "TTD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"TUNISIA": {"codigo_iso_alfa2": "TN", "codigo_iso_alfa3": "TUN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "TND", "idioma_codigo": None, "prefijo_movil": "216", "union_europea": False},
	"TURKEY": {"codigo_iso_alfa2": "TR", "codigo_iso_alfa3": "TUR", "codigo_iso_numerico": "None", "moneda_codigo_iso": "TRY", "idioma_codigo": None, "prefijo_movil": "90", "union_europea": False},
	"TURKMENISTAN": {"codigo_iso_alfa2": "TM", "codigo_iso_alfa3": "TKM", "codigo_iso_numerico": "None", "moneda_codigo_iso": "TMT", "idioma_codigo": None, "prefijo_movil": "993", "union_europea": False},
	"TURKS AND CAICOS ISLANDS": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "USD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"TUVALU": {"codigo_iso_alfa2": "TV", "codigo_iso_alfa3": "TUV", "codigo_iso_numerico": "None", "moneda_codigo_iso": "TVD", "idioma_codigo": "EN", "prefijo_movil": "688", "union_europea": False},
	"UGANDA": {"codigo_iso_alfa2": "UG", "codigo_iso_alfa3": "UGA", "codigo_iso_numerico": "None", "moneda_codigo_iso": "UGX", "idioma_codigo": "EN", "prefijo_movil": "256", "union_europea": False},
	"UKRAINE": {"codigo_iso_alfa2": "UA", "codigo_iso_alfa3": "UKR", "codigo_iso_numerico": "None", "moneda_codigo_iso": "UAH", "idioma_codigo": None, "prefijo_movil": "380", "union_europea": False},
	"UNITED ARAB EMIRATES": {"codigo_iso_alfa2": "AE", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "AED", "idioma_codigo": None, "prefijo_movil": "971", "union_europea": False},
	"UNITED KINGDOM": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "GBP", "idioma_codigo": None, "prefijo_movil": None, "union_europea": True},
	"UNITED STATES": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "USD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"UNITED STATES MINOR OUTLYING ISLANDS": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "USD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"URUGUAY": {"codigo_iso_alfa2": "UY", "codigo_iso_alfa3": "URY", "codigo_iso_numerico": "None", "moneda_codigo_iso": "UYU", "idioma_codigo": "ES", "prefijo_movil": "598", "union_europea": False},
	"UZBEKISTAN": {"codigo_iso_alfa2": "UZ", "codigo_iso_alfa3": "UZB", "codigo_iso_numerico": "None", "moneda_codigo_iso": "UZS", "idioma_codigo": None, "prefijo_movil": "998", "union_europea": False},
	"VANUATU": {"codigo_iso_alfa2": "VU", "codigo_iso_alfa3": "VUT", "codigo_iso_numerico": "None", "moneda_codigo_iso": "VUV", "idioma_codigo": None, "prefijo_movil": "678", "union_europea": False},
	"VATICAN CITY": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "EUR", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"VENEZUELA": {"codigo_iso_alfa2": "VE", "codigo_iso_alfa3": "VEN", "codigo_iso_numerico": "None", "moneda_codigo_iso": "VEF", "idioma_codigo": "ES", "prefijo_movil": "58", "union_europea": False},
	"VIET NAM": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "VND", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"VIRGIN ISLANDS (BRITISH)": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "USD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"VIRGIN ISLANDS (U.S.)": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "USD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"WALLIS AND FUTUNA": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "XPF", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"WESTERN SAHARA": {"codigo_iso_alfa2": "", "codigo_iso_alfa3": "None", "codigo_iso_numerico": "None", "moneda_codigo_iso": "MAD", "idioma_codigo": None, "prefijo_movil": None, "union_europea": False},
	"YEMEN": {"codigo_iso_alfa2": "YE", "codigo_iso_alfa3": "YEM", "codigo_iso_numerico": "None", "moneda_codigo_iso": "YER", "idioma_codigo": None, "prefijo_movil": "967", "union_europea": False},
	"ZAMBIA": {"codigo_iso_alfa2": "ZM", "codigo_iso_alfa3": "ZMB", "codigo_iso_numerico": "None", "moneda_codigo_iso": "ZMW", "idioma_codigo": "EN", "prefijo_movil": "260", "union_europea": False},
	"ZIMBABWE": {"codigo_iso_alfa2": "ZW", "codigo_iso_alfa3": "ZWE", "codigo_iso_numerico": "None", "moneda_codigo_iso": "ZWL", "idioma_codigo": "EN", "prefijo_movil": "263", "union_europea": False},
}