XXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXXX XXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXX
    X
    
    XXXXXXXXXXXXX XXXXXXXXXXXXX X
        XXXXXX XXXX
    X
XXXXXXXX
XXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXXXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXX
        XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX X XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX X XXXXXXX XX XXXXXXX XXXXX XXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXX XXXXXXX XXX XXXX XX XXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XXXXX XXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX X XXXXXX XXXXXXX XXXXX XX XXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX X XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX X XXXXXX XXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XXXX XX XXXXXXXXXXX XXXX XXXX XXX XXXXXX
            XXX XX XXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXX XXXX XXXX XXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XX XX XXXXXXXX XXXXXXX
            XXXXX XXXXXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXXXXXX XXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
            XXX XXXXXX XXXXXXXXXXX XXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXX XXXXXXX XXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXX XXX XXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXX XXXXXXXXX XXX XXX XXXXXX X XXXXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XX XXXXXXX XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    XXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
            XXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X
        XXX
    XXXXXXXXX
    XXX
        XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX